### ISSUE TITLE
Request for better documentation

### ISSUE THREAD

**Issue by arvindpdmn** [benmcollins/libjwt#10]
Since I am new to JWT, I was trying to find an introduction to what this repository is all about and how to use it. But all I find is doxygen generated docs, which I think are inadequate.

Specifically, I am generating JWT tokens on the server-side in PHP. My client application is in C and it needs to use the token when accessing the server API. I was looking for a client-side C implementation for JWT. Can it be done with this repo? Thanks.

This may not really be an "Issue." I did not find any other place to start a forum-like discussion thread. Feel free to close it.

**Comment by benmcollins** [comment]
I would suggest visiting http://jwt.io Your client likely just needs to pass the token to the server. The client generally doesn't parse or work with a JWT. It's just a token to it.

**Comment by oxr463** [comment]
It would be nice to have some code examples similar to libcurl, (See: https://curl.haxx.se/libcurl/c/example.html).

**Comment by benmcollins** [comment]
@oxr463 I agree. There's lots of code in `tests/` that would make a good starting point for creating some examples.
