### ISSUE TITLE
Memory allocation function definitions no longer match jwt-private.h header

### ISSUE THREAD

**Issue by rich617** [benmcollins/libjwt#104]
Hi, Ben. Looks like you made jwt_realloc, jwt_calloc, and jwt_strdup functions file-local to jwt.c. 

These are meant to be general-purpose memory utils that anything in the library can use, and so I'm not crazy about this decision. Just because they aren't used anywhere else doesn't mean they can't be used anywhere else. But, I'm not going to argue about it. They can always be made non-static again later if anyone needs them.

However, please also update jwt-private.h to remove the declarations for the functions that you made file-local. Otherwise, if anyone tries to use them in the future, it will result in linker errors. 

Thanks.

**Comment by benmcollins** [comment]
I'm a firm believer in making sure things are scoped as-used and not as-future-maybe.

They are already removed from the private header.

Thanks

**Comment by rich617** [comment]
Very efficient. Thank you.
