### ISSUE TITLE
Can we make new release please?

### ISSUE THREAD

**Issue by spinlockirqsave** [benmcollins/libjwt#107]
Hi Ben,

we would like to incorporate new changes in libjwt through released version. Is there any chance you have plans to release new version anytime soon?

regards,
Piotr

**Comment by benmcollins** [comment]
I can do that this weekend.

**Comment by spinlockirqsave** [comment]
Thank you very much Ben!

**Comment by spinlockirqsave** [comment]
Can we make new release please?

**Comment by benmcollins** [comment]
v1.12.0 released
