### ISSUE TITLE
This library does not play nicely with json-c

### ISSUE THREAD

**Issue by wkborn** [benmcollins/libjwt#113]
In projects that use both json-c and libjwt, multiple functions result in segmentation faults. Examples are jwt_add_grant, jwt_add_grant_int, and jwt_encode_str. I assume this is due to internal namespace collisions between the libraries. This would probably be a good thing to fix, as I would assume many projects would like to use both.

**Comment by benmcollins** [comment]
If there are symbol name clashes, I'd need an example program that links to both and causes the problem so I can work on fixing it, please.

Thanks

**Comment by wkborn** [comment]
```
#include<stdio.h>
#include <json-c/json.h>
#include<jwt.h>

int main(){
    jwt_t *jwt;
    jwt_new(&jwt);

    jwt_add_grant_int(jwt,"test",1);

    char* tokraw = jwt_encode_str(jwt);
    char* tokenc = jwt_encode_str(jwt);

    printf("raw:\n%s\nenc:\n%s\n", tokraw, tokenc);
    return 0;
}
```

**Comment by wkborn** [comment]
I have looked into this deeper, and it is actually name conflicts are between jansson and json-c. I guess my fastest short term solution is to migrate my own code to jansson. Your library links to jansson to do internal json manipulation and parsing, and since json-c uses a lot of the same naming conventions, there is bound to be overlap. Sad that those two projects don't deconflict.

**Comment by wkborn** [comment]
The more I am looking at this, the more I think the actual solution would be to leave the code as is and leave a comment in the readme. Problem is definitely between jansson and json-c.

**Comment by TomzBench** [comment]
Is there any interest in a json abstraction layer (much like the way crypto is handled).  You can make a jwt_json() layer and implement different JSON parsers.  I would like to see this library support mbedtls / wolfssl for the crypto options, and also jsmn for a JSON parser.  Then this library could work more easily on light weight embedded systems.

**Comment by benmcollins** [comment]
I would definitely be interested in being able to use Jansson and JSON-C interchangeably like we do for GnuTLS and OpenSSL.

**Comment by wkborn** [comment]
I just moved my code base to jansson. It was very similar and everything works now.

**Comment by benmcollins** [comment]
If this means that you no longer have an interest in doing the abstraction, please close this issue :)

Thanks for getting back on the progress through your issues.

**Comment by TomzBench** [comment]
I'm still interested in abstraction (different person from who opened the issue) but will use jsmn https://github.com/zserge/jsmn as the "other" json parser. Other parsers could be added later.

jsmn is more friendly on micro controller environments. Right now all my microcontroller projects use basic authentication and if this lib could run on a micro I could switch my apps to use jwt...

(To complete microcontroller support the crypto layer would also have to be extended to support either mbedtls or wolfssl)...

Before submitting any PR's though it would be nice if the code formatting tool could be in place. https://github.com/benmcollins/libjwt/pull/112

**Comment by benmcollins** [comment]
Oddly enough, I've done some work on mbedTLS with LibJWT already.

**Comment by TomzBench** [comment]
That's great - Is it in this repo?

**Comment by benmcollins** [comment]
No. I'll have to dig it up. It actually wasn't all that hard, but it needs some work so it detects that all the proper stuff is enabled in the mbedTLS library.

**Comment by TomzBench** [comment]
If you find it you can put it on an mbed branch and I can work on the cmake build options / flags etc...

**Comment by wkborn** [comment]
I'm going to close this issue. While having different TLS module support makes sense, this is probably not the best point of effort given that jansson and json-c are so similar.

**Comment by xback** [comment]
> No. I'll have to dig it up. It actually wasn't all that hard, but it needs some work so it detects that all the proper stuff is enabled in the mbedTLS library.

What is the status on this support?
If I read above comment, it looks like it was nearly finished?
Could you share the current code?

Thanks!
