### ISSUE TITLE
May I ask about failure of PEM_read_bio_PUBKEY (jwt-openssl.c)

### ISSUE THREAD

**Issue by kojaechul** [benmcollins/libjwt#116]
Hello.
I would like to ask how to veify ES256 using libjwt.

I downloaded libjwt-master.zip at 14.Jan from Github
and compile like this at extract directory of libjwt-master.zip
autoreconf -i
./confiugre
make all
make insall

I installed jansson-master.zip also before making libjwt.
OS is CentOS Linux release 7.3.1611
and gcc version 4.8.5 and openssl/openssl-libs/openssl-devl 1.0.1e

After I Installed, I move to example directory and tested.
I got "invalid jwt" message.

./jwtauth --key pub.pem --alg ES256 -c scope=xxx -c aud=xxx -c iss=xxx -c sub=xxx access.jwt

jwt verification: jwt access.jwt pubkey pub.pem algorithm ES256
pub key loaded pub.pem (177)!
jwt loaded access.jwt (312)!
invalid jwt

I looked for the error point using gdb 
and I found PEM_read_bio_PUBKEY function returnd NULL (jwt-openssl.c/jwt_verify_sha_pem)

I simulated jwt value and key at https://jwt.io/#debugger-io and got message verify signiture verified

I write jwt token and public key.
please Let me know how to solve this situation.

Thank you.

token
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBTUYiLCJleHAiOjE1ODExNDU0NDYsImlzcyI6Im5yZjAwMDAxLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMSIsInNjb3BlIjoibmFtZi1jb21tIiwic3ViIjoiM2ZmMzUxMzctYjVmYi00YThkLTgwNWItODU5NTQ4MzVkMzllIn0.U8PzyKWzIVv79VubqDT4bQIWqlzThbdchdMQdJKEYewUD3A3Nk25CzvDenxiXWXwA-3S35ZyBEBKnygXSsMGYw

public key
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnfTEFNHSsdcfxxAruGbx/g5OUV4plxqSAKvilKDX6Gt0ume3+XrY4lQAwZ2AJg19pnuGyl3O7RYiuZJqC+oCqg==
-----END PUBLIC KEY-----

**Comment by benmcollins** [comment]
I show this with your PUB key and JWT:

    ./jwtauth --key pub.pem --alg ES256 access.jwt
    jwt verification: jwt access.jwt pubkey pub.pem algorithm ES256
    pub key loaded pub.pem (177)!
    jwt loaded access.jwt (312)!
    jwt decoded successfully!
    JWT is authentic! sub: 3ff35137-b5fb-4a8d-805b-85954835d39e
    
    {
        "alg": "ES256",
        "typ": "JWT"
    }
    .
    {
        "aud": "AMF",
        "exp": 1581145446,
        "iss": "nrf00001-0000-0000-0000-000000000001",
        "scope": "namf-comm",
        "sub": "3ff35137-b5fb-4a8d-805b-85954835d39e"
    }

**Comment by benmcollins** [comment]
Here's the actual files from your info. Maybe the files aren't correct?
[test-es256.zip](https://github.com/benmcollins/libjwt/files/4174171/test-es256.zip)

**Comment by kojaechul** [comment]
Thanks Your comment ^^
I tried to test as you've done with out claims parameter.
I got message "invalid jwt" .

I tried to download libjwt-master.zip from This Github and unpack.
I did these command like below as root 

autoreconf -i
configure
make all
make check ( jwt_new.c:9:19: fatal error: check.h: no file no directory #include <check.h>)
and make install

I move to example directory and copy token and key files from test-es256.zip 
# ls
CMakeLists.txt  Makefile  Makefile.am  Makefile.in  jwtauth  jwtgen  main-auth.c  main-auth.o  main-gen.c  main-gen.o

# ./jwtauth --key pub.pem --alg ES256 access.jwt
jwt verification: jwt access.jwt pubkey pub.pem algorithm ES256
pub key loaded pub.pem (177)!
jwt loaded access.jwt (312)!
invalid jwt

I move to .libs and tried again, I got the same message

So I check jwtauth's library link
# ldd jwtauth
        linux-vdso.so.1 =>  (0x00007ffc14b8d000)
        libjwt.so.0 => /usr/local/lib/libjwt.so.0 (0x00007fef546c6000)
        libjansson.so.4 => /usr/local/lib/libjansson.so.4 (0x00007fef544b7000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007fef54231000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fef53e47000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fef53a85000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fef53837000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fef53550000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fef5334b000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fef53119000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fef52f15000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fef52cfe000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fef548cf000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fef52aef000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fef528eb000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fef526d0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fef524b4000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fef5228c000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fef5202b000)

Is there any other points that I can check?
I attach the history that I did from unpack to test

I Really appreciate your help . and Please let me to solve 

Thank you.
[my_act.txt](https://github.com/benmcollins/libjwt/files/4174217/my_act.txt)

**Comment by benmcollins** [comment]
I would say to install the GNU check library so you can run the test suite. See what that might tell us. What version of OpenSSL are you using?

**Comment by kojaechul** [comment]
Hello..
Thanks Your commet. ^__^

OpenSSL version is 1.0.1e.

~:0> openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013

AND RPM Package were installed like below.

~:0> rpm -qa | grep openssl
openssl-libs-1.0.1e-60.el7.x86_64
openssl-1.0.1e-60.el7.x86_64
openssl-devel-1.0.1e-60.el7.x86_64
openssl-libs-1.0.1e-60.el7.i686
openssl098e-0.9.8e-29.el7.centos.3.x86_64
openssl-devel-1.0.1e-60.el7.i686

Thank You.

**Comment by kojaechul** [comment]
I downloaded openssl-1.1.1d 
and like this openssl version.

And I got success message
./jwtAuth --key pub.pem --alg ES256 access.jwt 
jwt verification: jwt access.jwt pubkey pub.pem algorithm ES256
11111
pub key loaded pub.pem (177)!
jwt loaded access.jwt (312)!
jwt decoded successfully!
JWT is authentic! sub: 3ff35137-b5fb-4a8d-805b-85954835d39e

{
    "alg": "ES256",
    "typ": "JWT"
}
.
{
    "aud": "AMF",
    "exp": 1581145446,
    "iss": "nrf00001-0000-0000-0000-000000000001",
    "scope": "namf-comm",
    "sub": "3ff35137-b5fb-4a8d-805b-85954835d39e"
}

I think 
when I use libjwt package to veriy ES256, openssl version 1.0.1 is not compatible.
But I can't upgrate openssl version. so It is a problem to use libjwt for ES256.
Is there any idea, can I use my openssl version for libjwt ES256 verification?

Thank you.

**Comment by benmcollins** [comment]
Sounds like the FIPS version had some algorithms that were disabled to meet FIPS criteria, which made LibJWT not work.

Thanks for following up.

**Comment by kojaechul** [comment]
Thanks for your comment. 
If you don't mind , could you give me more explanation?
As I understood, server Installed openssl version (openssl-libs-1.0.1e-60.el7.x86_64) on my server
has limitation to verity ES256 in US regal.
But I'm not sure if I understood correctly.
I would like to know more detail..So Please let me know more detail.

Thank you.

**Comment by benmcollins** [comment]
> openssl version
    OpenSSL 1.0.1e-fips 11 Feb 2013

This shows you installed a FIPS version of OpenSSL. FIPS is a cryptographic certification. Certain things are disabled in OpenSSL in order to satisfy FIPS requirements in this version. I'm not sure exactly what was disabled. It's highly likely it was the EC curve you chose for your Pub/Private EC key.

**Comment by kojaechul** [comment]
I'm really appreciate your help.
Thank you and have a good day.^^
