### ISSUE TITLE
Building without Openssl variant library doesn't carry the "-gnutls" filename suffix

### ISSUE THREAD

**Issue by rmackinnon** [benmcollins/libjwt#121]
Greatings,

Got bit by this earlier today while building this as a requirement for a downstream. Everything builds fine (regardless of use of with/without openssl), but I have found the output file when building the variant where GnuTLS is used doesn't differentiate itself. The downstream seems to think this is a thing, and expects "libjwt-gnutls.so*" to exist. If that is not the case, I'll happily go file a bug there, and ensure that it is looking for the correct file. ;)

**Comment by benmcollins** [comment]
That's never been the case. The idea is that the user of LibJWT should not even need to be aware of which backend crypto is being used. GnuTLS and OpenSSL do not conflict as linked libraries that I am aware of.

LibJWT has never done naming this way, so I suspect some Linux distro has introduced this scheme as a way to have both variants installable at once.

**Comment by rmackinnon** [comment]
No worries man, I had to hedge my bets on where this was. Personally I too have never seen this, but also was unfamiliar with your library. -_o_- I will happily take this up with the downstream.
