### ISSUE TITLE
jwt_encode_str return null instead of token

### ISSUE THREAD

**Issue by georgii-ivanov** [benmcollins/libjwt#124]
```
        jwt_t *jwt;
        jwt_new(&jwt);
        jwt_add_grant_int(jwt, "jti", pss->user_id);
        jwt_set_alg(jwt, JWT_ALG_RS256, (unsigned char *)SESSION_KEY_APP_SECRET, strlen(SESSION_KEY_APP_SECRET));
        char *out = jwt_encode_str(jwt);
        Logger::Notice("%s\n", out);
```

This doesn't work just outputs null instead of a token string.

When I comment `jwt_set_alg` line it starts working...

What am I doing wrong? Or something wrong with the library?

**Comment by benmcollins** [comment]
As noted, [here](http://benmcollins.github.io/libjwt/group__jwt__encode.html#gae660380bf45c955fd8909b14dae2441a). If jwt_encode_str returns NULL, then you need to check `errno` to see why.

At first glance, I suspect you are providing something that is not a PEM encoded RSA key.
