### ISSUE TITLE
jwt_new.c:9:19: check.h: No such file or directory

### ISSUE THREAD

**Issue by jaggzh** [benmcollins/libjwt#125]
$ make check
Making check in include
make[1]: Entering directory '/home/jaggz/github/libjwt/include'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/jaggz/github/libjwt/include'
Making check in libjwt
make[1]: Entering directory '/home/jaggz/github/libjwt/libjwt'
make[1]: Leaving directory '/home/jaggz/github/libjwt/libjwt'
Making check in examples
make[1]: Entering directory '/home/jaggz/github/libjwt/examples'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/jaggz/github/libjwt/examples'
Making check in tests
make[1]: Entering directory '/home/jaggz/github/libjwt/tests'
make  jwt_new jwt_grant jwt_header jwt_dump jwt_encode jwt_rsa jwt_ec jwt_validate
make[2]: Entering directory '/home/jaggz/github/libjwt/tests'
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall  -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_new.o -MD -MP -MF .deps/jwt_new.Tpo -c -o jwt_new.o jwt_new.c
jwt_new.c:9:19: fatal error: check.h: No such file or directory
compilation terminated.
Makefile:679: recipe for target 'jwt_new.o' failed
make[2]: *** [jwt_new.o] Error 1
make[2]: Leaving directory '/home/jaggz/github/libjwt/tests'
Makefile:1000: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/jaggz/github/libjwt/tests'
Makefile:487: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error

**Comment by benmcollins** [comment]
You need to install the GNU Check library. On Debian/Ubuntu, the package is "check"

**Comment by jaggzh** [comment]
Thank you very much. Did I miss a fatal error when running configure?

**Comment by benmcollins** [comment]
The test suite is optional. So, no, it was not a fatal error. Configure would have shown that it could not find check.h or lib check.a.
