### ISSUE TITLE
Missing `json_typeof` checks

### ISSUE THREAD

**Issue by marcin-rzeznicki** [benmcollins/libjwt#128]
The functions: `jwt_get_grant_int` and `jwt_get_grant_bool` should check the JSON value type and signal an error on mismatch, instead of trying to convert blindly. Currently, integers become silently 0 and there is no way to determine if received JSON was correct.

**Comment by marcin-rzeznicki** [comment]
Ping @benmcollins WDYT?

**Comment by benmcollins** [comment]
This sounds logical.
