### ISSUE TITLE
Please add a function that returns grants as `json_t`

### ISSUE THREAD

**Issue by marcin-rzeznicki** [benmcollins/libjwt#129]
The current API can only get the grant value (other than JSON `int` or `string`) as a JSON string. This effectively forces the caller to parse it again. This is sub-optimal at best, as the same piece of JSON is parsed twice. To remedy this, the API should offer a way to retrieve the underlying `json_t` (possibly cloned).

**Comment by benmcollins** [comment]
The only problem with this is I do not want to expose JANSSON to the LibJWT caller.

Right now, theoretically, the JSON parsing backend can be changed without affecting the API/ABI of programs compiled against LibJWT. I also do not want LibJWT to have so much functionality, that it, itself, is used to parse JSON in general; just JWT strings.

So there has to be a balance here to retain LibJWT's agnostic view of the JSON parsing backend it uses, but also allow the caller to retrieve common JSON values as C-type values.

**Comment by marcin-rzeznicki** [comment]
Thanks a lot for a quick response! Fair enough, I rest my case.
