### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by marcin-rzeznicki** [benmcollins/libjwt#137]
Hello,
It is not so much an issue as a kind request. Would it be justified to make a new, perhaps a minor, release? I'm personally interested in 5621e0c out the door so that I can refer to the released version without doing too many workarounds (https://github.com/commercialhaskell/stackage/pull/5648).  I'd be grateful. Thanks

**Comment by benmcollins** [comment]
Sure thing. I'll try to get it out by Monday.

**Comment by marcin-rzeznicki** [comment]
Thank you, I appreciate it. Take your time.

**Comment by benmcollins** [comment]
v1.12.1 released

**Comment by marcin-rzeznicki** [comment]
Thanks a lot!
