### ISSUE TITLE
E: The repository 'http://ppa.launchpad.net/ben-collins/libjwt/ubuntu bionic Release' does not have a Release file.

### ISSUE THREAD

**Issue by timotheecour** [benmcollins/libjwt#138]
the ubuntu version is too old, so I was trying to get a newer one with
`sudo add-apt-repository ppa:ben-collins/libjwt`

but it gives error:

E: The repository 'http://ppa.launchpad.net/ben-collins/libjwt/ubuntu bionic Release' does not have a Release file.

(on: Ubuntu 18.04.5 LTS)

**Comment by benmcollins** [comment]
I've not released builds for bionic, yet. I'll try to get this done soon with v1.12.1.

**Comment by benmcollins** [comment]
LibJWT is included in bionic.
