### ISSUE TITLE
numeric values not found

### ISSUE THREAD

**Issue by fitzyjoe** [benmcollins/libjwt#14]
When I try to get the "exp" or "iat" grant (created by other jwt libraries), NULL is returned.  This is because those values are not stored as strings (and should not be stored as strings according to the spec.)

`jwt_get_grant` calls `get_js_string` which calls `json_string_value`

I made functions

`jwt_get_grant_int` which calls `get_js_int` which calls `json_integer_value`

Here's the JWT that I was parsing.  I printed this via `jwt_dump_str`:

<pre>{
    "typ": "JWT",
    "alg": "HS256"
}
.
{
    "emailAddress": "joefitz@teslagov.com",
    "exp": 1473905589,
    "firstName": "Joe",
    "iat": 1473819189,
    "iss": "RAMPART",
    "lastName": "Fitz",
    "personId": "0f416f7c-da9e-4fe6-8447-9a5b3b6d79c5",
    "roles": [
        "rampartadmin",
        "someappuser"
    ],
    "sub": "0f416f7c-da9e-4fe6-8447-9a5b3b6d79c5"
}</pre>

But I was unable to get the "exp" or "iat" values with `jwt_get_grant`.  I think that `jwt_set_grant` will not be compliant for "exp" and "iat" values because it will set them as strings.

I have a branch if you'd like a pull request.

**Comment by fitzyjoe** [comment]
Looks like there is a pull request to address this problem, but in a more broad way - to support JSON.  Doesn't this seem like a critical piece?  How else can you validate expiration dates of tokens (that were made as integers by other spec compliant libraries)?  Last movement on that pull request was in April.  Is this dead?

**Comment by benmcollins** [comment]
Fixed in cd227d70c497350a56c1759999a08455f5a55612
