### ISSUE TITLE
Trouble generating jwt with nested json

### ISSUE THREAD

**Issue by p-gentili** [benmcollins/libjwt#145]
Hi
I'm try to generate a jwt of the following json:

{
"key1": "value1",
"key2: {"subkey1": "subvalue1"}
}

is it possible to encode something like this with the example main-gen.c? If not how could I tweak it to achieve what I want?

Thanks

**Comment by benmcollins** [comment]
Hello,

What you want is `jwt_add_grants_json()` and `jwt_get_grants_json()`. You can find their usage in `jwt.h`.
