### ISSUE TITLE
libjwt 1.13.1 does not compile anymore with jansson 2.13.1 on Windows using cmake

### ISSUE THREAD

**Issue by micwinxx** [benmcollins/libjwt#154]
OS:
- Windows 10

involved software:
- Cmake version: 3.21.1
- VS 2019
- (openssl-1.1.1k self build via its build mechanism)

Build process for jansson 2.13.1
- extract and untar provided tar.gz file from https://github.com/akheron/jansson/archive/refs/tags/v2.13.1.tar.gz and cd into created directory
```
mkdir build
cd build
cmake.exe .. -DJANSSON_BUILD_DOCS=OFF
cmake.exe --build . --config Release
```

Trying to build libjwt 1.13.1
- extract and untar provided tar.gz file from `https://github.com/benmcollins/libjwt/archive/refs/tags/v1.13.1.tar.gz` and cd into created directory
```
mkdir build
cd build
cmake .. -DOPENSSL_ROOT_DIR="c:\openssl-1.1.1k-install" -Djansson_DIR="c:\jansson-2.13.1\build"
```

Here the end of the output of the last command which fails:

```
CMake Error at C:/jansson-2.13.1/build/janssonConfig.cmake:3 (include):
  include could not find requested file:

    C:/jansson-2.13.1/build/janssonTargets.cmake
Call Stack (most recent call first):
  libjwt/CMakeLists.txt:46 (find_package)


CMake Error at C:/jansson-2.13.1/build/janssonConfig.cmake:4 (check_required_components):
  Unknown CMake command "check_required_components".
Call Stack (most recent call first):
  libjwt/CMakeLists.txt:46 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/libjwt-1.13.1/build/CMakeFiles/CMakeOutput.log".
```

The content of `janssonConfig.cmake` is:

```
include("${CMAKE_CURRENT_LIST_DIR}/janssonTargets.cmake")
check_required_components("jansson")
```

The file that is tried to be included above `janssonTargets.cmake` can be found in  actually `C:/jansson-2.13.1/build/CMakeFiles\Export\cmake\janssonTargets.cmake` so it looks like that the cmake mechanism is not working correctly and the cmake variables, e.g., CMAKE_CURRENT_LIST_DIR is not correctly set.

I have not seen or found any workaround for that.

But I was able to compile libjwt 1.12.1
- extract and untar provided tar.gz file from `https://github.com/benmcollins/libjwt/archive/refs/tags/v1.12.1.tar.gz` and cd into created directory

```
mkdir build
cd build
cmake.exe .. -DOPENSSL_ROOT_DIR="c:\openssl-1.1.1k-install" -DJANSSON_LIBRARY="c:\jansson-2.13.1\build\lib\Release" -DJANSSON_INCLUDE_DIR="c:\jansson-2.13.1\build\include"
cmake.exe --build . --config Release
```

So the "old" way of the cmake setup is working. I believe the change causing the build process on the newer/current libjwt version to fail was introduced with https://github.com/benmcollins/libjwt/pull/141.

I hope that this is enough information to tackle this issue, it looks like a bug to me.
If you need any more information or have a workaround or fix, please let me know.

**Comment by dafanasiev** [comment]
I try make with cmake on nix with same problems. So, I just "fix" jansson build
{code}
...
		cp ./cmake/* ./CMakeFiles/Export/lib && \
		cp ./CMakeFiles/Export/lib/cmake/jansson/* ./CMakeFiles/Export/lib
{code}

after that I set env `jansson_DIR="/bla/bla/bla/jansson/build/CMakeFiles/Export/lib"` before run cmake  for libjwt

**Comment by micwinxx** [comment]
@dafanasiev, hanks for the suggestion, but on Windows the directory structure is different and there exists no `lib` directory in `CMakeFiles\Export` so I'm unsure what to copy and where to copy it.

```
dir CMakeFiles\Export\
...
09/10/2021  07:10 AM    <DIR>          .
09/10/2021  07:10 AM    <DIR>          ..
09/10/2021  07:10 AM    <DIR>          cmake
...
```

@andrejlevkovitch, maybe you have an idea on the whole cmake installation procedure since the change was introduced with your PR referenced above. Maybe we should revert to the old behavior which has been working for quite some time.

**Comment by andrejlevkovitch** [comment]
@micwinxx @dafanasiev Hi guys! Of course cmake could not find config file, because you didn't install jansson - file in build directory just not valid! You should install jansson at first, like:

```sh
cmake -DCMAKE_INSTALL_PREFIX="any directory, even your build directory" ..
cmake --build . --target install
```

after that you can run libjwt build as:

```sh
cmake -DCMAKE_PREFIX_PATH="path to jansson install dir" ..
```

**Comment by micwinxx** [comment]
@andrejlevkovitch, thanks. This works for me, even though is looks a bit like a work around because one needs to install jansson.

Now when I get to the point where I want to build and install libjwt with `cmake.exe --build . --config Release --target install`
it will fail with:

```
  Building Custom Rule C:/my_path/libjwt-1.13.1/examples/CMakeLists.txt
cl : command line error D8021: invalid numeric argument '/Werror' [C:\my_path\libjwt-1.13.1\build\example
s\jwtauth.vcxproj]
  Building Custom Rule C:/my_path/libjwt-1.13.1/examples/CMakeLists.txt
cl : command line error D8021: invalid numeric argument '/Werror' [C:\mypath\libjwt-1.13.1\build\example
s\jwtgen.vcxproj]
```

I find it starnge that the CFLAGS are gcc based even though VS is used. If I adjust the gcc CFLAGS to VS CFLAGS by hand, I then get

```
C:\my_path\libjwt-1.13.1\examples\main-gen.c(11,10): fatal error C1083: Cannot open include file: 'getopt
.h': No such file or directory [C:\my_path\libjwt-1.13.1\build\examples\jwtgen.vcxproj]
``` 

Any ideas on that?

**Comment by andrejlevkovitch** [comment]
@micwinxx on Windows you should manually set needed [cmake generator](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html). Check output of `cmake -G` and select needed generator. I think after it all should be fine

**Comment by micwinxx** [comment]
@andrejlevkovitch, thank you for the suggestion. The default is already selected to be `-G "Visual Studio 16 2019"` but also when explicitly specifying it, the behavior does not change and I run into the above error. I also tried `-G "NMake Makefiles"` but then after running `nmake` the error is just similar to the above:

```
...
[ 50%] Linking C static library jwt.lib
[ 50%] Built target jwt
[ 62%] Building C object examples/CMakeFiles/jwtgen.dir/main-gen.c.obj
cl : Command line error D8021 : invalid numeric argument '/Werror'
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0x2'
...
```

**Comment by andrejlevkovitch** [comment]
@micwinxx looks like examples and tests supports only gcc compiler. Try configure with `-DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF`

**Comment by micwinxx** [comment]
@andrejlevkovitch thank you a lot, that works for me.

I will close this issue now, since the build now works. If someone wants to improve the cmake build process and also integrate test and example builds on Windows, this should be tackled in another GH issue.
