### ISSUE TITLE
Audience check

### ISSUE THREAD

**Issue by kfox1111** [benmcollins/libjwt#161]
In an oidc token, audience can be an array. This allows multiple valid audiences to be specified and the target audience should be checked if its in the list in that case, rather then just comparing the arrays directly. There does not seem to be a way to validate the audience is in the list in the code currently.

**Comment by benmcollins** [comment]
In `jwt_validate()` there is this code:

        /* Validate replicated audience (might be array or string) */
        js_val_1 = json_object_get(jwt->headers, "aud");
        js_val_2 = json_object_get(jwt->grants, "aud");
        if (js_val_1 && js_val_2 && !json_equal(js_val_1, js_val_2))
                jwt_valid->status |= JWT_VALIDATION_AUD_MISMATCH;

According to the docs on Jansson:

> Two arrays are equal if they have the same number of elements and each element in the first array is equal to the corresponding element in the second array.

So it seems This is handled, but I'd be happy to include a test case to verify.

**Comment by kfox1111** [comment]
In the case of the jwt audience being an array, you should not be testing the services audience matches 1 to 1. but that the audience of the client (single string) is in the list presented by the audience property of the jwt (M items).

**Comment by benmcollins** [comment]
I see. Can you make sure I understand this. So if the token has

    { "aud": "foo" }

and the validation accepts

    { "aud": ["foo", "bar", "baz"] }

then it should validate. I haven't read the part in the RFC all that much on this, but let me ask another example. If the token contains:

    { "aud": ["foo", "bar"] }

and for verification I have these:

     { "aud": ["foo", "baz", "bob"] }

Should it validate because `"foo"` matches (OR) or should it fail because `"bar"` didn't (AND)?

**Comment by kfox1111** [comment]
The other way around. A client has just one name.

Its valid for the jwt token to have multiple audiences, like: { "aud": ["foo", "bar"] }

If your client is 'foo', then this token is valid for you.
If your client is 'bar', this token is also valid for you.
If your client is 'bob', then this token is not for you and should  be rejected.

A more concrete example may help:
Say you have two services/clients. 'kubernetes-dashboard' and 'kubernetes-apiserver'

Your IDP can create a token {"aud":["kubernetes-dashboard","kubernetes-apiserver"]

Your browser hands that token to service 'kubernetes-dashboard'. The webui in that client, validates against 'kubernetes-dashboard' and sees its valid. Then the webservice can hand its token directly to the rest api of kubernetes-apiserver as the user interacts with the website, and the server 'kubernetes-apiserver' will also honor the token as its for client 'kubernetes-apiserver' and fulfill the request the initial user made.
