### ISSUE TITLE
OpenSSL 3?

### ISSUE THREAD

**Issue by wolfkor** [benmcollins/libjwt#165]
Is it planned to switch to OpenSSL 3 ?

**Comment by benmcollins** [comment]
I just compiled against 3.0.7 without any issues other than a few "deprecated" warnings. All tests passed.

**Comment by benmcollins** [comment]
Did some extensive testing and research. There's no clear way to remove the use of deprecated functions that retrieve the EC key from the EVP PKey. However, everything works as expected. All tests pass, including valgrind tests.
