### ISSUE TITLE
NEWS file?

### ISSUE THREAD

**Issue by wpoely86** [benmcollins/libjwt#166]
I see that version 1.14.0 got tagged yesterday. Is there any way of knowing what has changed since 1.13.0 (other then `git log`)? Is it just bug fixes, something new got added?

From the `git log` is appears as fixing stuff, correct?

I'm a Fedora maintainer for libjwt so it would be nice to know if there are any dragons to watch out for :wink:

**Comment by benmcollins** [comment]
No other way to know than git log. Just bug fixes. Thanks for maintaining the package.

**Comment by benmcollins** [comment]
If anything does at some point break ABI or API I’ll make it very prominent on the release.
