### ISSUE TITLE
jansson.h is missing

### ISSUE THREAD

**Issue by thealexparshin** [benmcollins/libjwt#169]
thinker:~/workspace/libjwt$ cmake .
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.5")  
-- Checking for one of the modules 'jansson'
-- version from configure.ac: '1.15.2'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alexeyp/workspace/libjwt

thinker:~/workspace/libjwt$ make 
[ 12%] Building C object libjwt/CMakeFiles/jwt.dir/base64.c.o
[ 25%] Building C object libjwt/CMakeFiles/jwt.dir/jwt-openssl.c.o
In file included from /home/alexeyp/workspace/libjwt/libjwt/jwt-openssl.c:21:
/home/alexeyp/workspace/libjwt/libjwt/jwt-private.h:11:10: fatal error: jansson.h: No such file or directory
   11 | #include <jansson.h>
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by benmcollins** [comment]
Do you have jansson installed and if so, where?

**Comment by benmcollins** [comment]
Also I don’t directly support the cmake build. The auto tools build is preferred. If there’s issues with the cmake build, you’ll need to contact the person who contributed that code.

**Comment by thealexparshin** [comment]
Installing libjansson resolved it. The use of auto tools is a bit old fashion. IMHO, CMake is de-facto standard today, and your CMake file worked fine, except it didn't try detecting libjansson (and I didn't know about that library).

**Comment by benmcollins** [comment]
bcollins@maClara:~/libjwt$ cat CMakeLists.txt libjwt/CMakeLists.txt tests/CMakeLists.txt examples/CMakeLists.txt | sed -e '/^$/d' -e '/^#/d' | wc -l
       213
    bcollins@maClara:~/libjwt$ cat Makefile.am libjwt/Makefile.am tests/Makefile.am examples/Makefile.am configure.ac | sed -e '/^$/d' -e '/^#/d' | wc -l
       100

Autotools is less than half the supporting code, plus it actually works. If you or someone else can maintain the CMake build such that it actually works, maybe I'd be convinced.

Not to mention, no one has added support for a proper SOVERSION on the CMake build, so if you plan on keeping updated with the upstream builds, you're going to run into issues unless you're using the autotools to build it.

I appreciate your opinion, but I don't believe autotools is old fashion, unless by that you mean "stable, tested, simple, and proven".
