### ISSUE TITLE
fatal error: jwt.h: No such file or directory

### ISSUE THREAD

**Issue by kvijay1918** [benmcollins/libjwt#172]
jwt-check.c:1:10: fatal error: jwt.h: No such file or directory
    1 | #include <jwt.h>
      |          ^~~~~~~
compilation terminated.

Am getting this jwt.h file not found error. It seems, this file is not getting copied either to /usr/local/include or /usr/include by following the below commands,

With GNU Make: Use autoreconf -i to create project files and run ./configure.

make all: build library.
make check: build and run test suite.

up to make check, looks all fine.

Even if I copied it manually to any one of those mentioned location, it says,

root@vj-node:~/vijay/jwt/c-code# gcc -o main jwt-check.c -ljwt
/usr/bin/ld: cannot find -ljwt
collect2: error: ld returned 1 exit status

Looks like libjwt is not installed properly.

my .c file doesn't contain any code.. its simply,

#include <jwt.h>
void main(){

}

that's it.

Help me to resolve this.

**Comment by kvijay1918** [comment]
root@vj-ansible-node:~/vijay/jwt/libjwt# **autoreconf -i**
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:5: installing './compile'
configure.ac:5: installing './config.guess'
configure.ac:5: installing './config.sub'
configure.ac:3: installing './install-sh'
configure.ac:3: installing './missing'
examples/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'

***************************************************
root@vj-ansible-node:~/vijay/jwt/libjwt# **ls**
aclocal.m4      cmake           compile       config.sub  configure.ac  dist         doxygen.mk  images   install-sh  LICENSE    m4           Makefile.in  README.cmake.md  test-driver
autom4te.cache  CMakeLists.txt  config.guess  configure   depcomp       doxygen.cfg  examples    include  libjwt      ltmain.sh  Makefile.am  missing      README.md        tests

**************************************************

root@vj-ansible-node:~/vijay/jwt/libjwt# **./configure**
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for OPENSSL... yes
checking for JANSSON... yes
checking for CHECK... yes
checking for valgrind... no
checking whether to build with code coverage support... no
checking for doxygen... no
configure: WARNING: doxygen not found - will not generate any doxygen documentation
checking for perl... /usr/bin/perl
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating libjwt/Makefile
config.status: creating examples/Makefile
config.status: creating tests/Makefile
config.status: creating libjwt/libjwt.pc
config.status: creating dist/Makefile
config.status: creating dist/libjwt.spec
config.status: creating libjwt/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
root@vj-ansible-node:~/vijay/jwt/libjwt#

***************************************************
root@vj-ansible-node:~/vijay/jwt/libjwt# make all
Making all in include
make[1]: Entering directory '/root/vijay/jwt/libjwt/include'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/vijay/jwt/libjwt/include'
Making all in libjwt
make[1]: Entering directory '/root/vijay/jwt/libjwt/libjwt'
make  all-am
make[2]: Entering directory '/root/vijay/jwt/libjwt/libjwt'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I../include    -Wall  -I/usr/local/include    -D_GNU_SOURCE -g -O2 -MT libjwt_la-jwt.lo -MD -MP -MF .deps/libjwt_la-jwt.Tpo -c -o libjwt_la-jwt.lo `test -f 'jwt.c' || echo './'`jwt.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -Wall -I/usr/local/include -D_GNU_SOURCE -g -O2 -MT libjwt_la-jwt.lo -MD -MP -MF .deps/libjwt_la-jwt.Tpo -c jwt.c  -fPIC -DPIC -o .libs/libjwt_la-jwt.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -Wall -I/usr/local/include -D_GNU_SOURCE -g -O2 -MT libjwt_la-jwt.lo -MD -MP -MF .deps/libjwt_la-jwt.Tpo -c jwt.c -o libjwt_la-jwt.o >/dev/null 2>&1
mv -f .deps/libjwt_la-jwt.Tpo .deps/libjwt_la-jwt.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I../include    -Wall  -I/usr/local/include    -D_GNU_SOURCE -g -O2 -MT libjwt_la-base64.lo -MD -MP -MF .deps/libjwt_la-base64.Tpo -c -o libjwt_la-base64.lo `test -f 'base64.c' || echo './'`base64.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -Wall -I/usr/local/include -D_GNU_SOURCE -g -O2 -MT libjwt_la-base64.lo -MD -MP -MF .deps/libjwt_la-base64.Tpo -c base64.c  -fPIC -DPIC -o .libs/libjwt_la-base64.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -Wall -I/usr/local/include -D_GNU_SOURCE -g -O2 -MT libjwt_la-base64.lo -MD -MP -MF .deps/libjwt_la-base64.Tpo -c base64.c -o libjwt_la-base64.o >/dev/null 2>&1
mv -f .deps/libjwt_la-base64.Tpo .deps/libjwt_la-base64.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I../include    -Wall  -I/usr/local/include    -D_GNU_SOURCE -g -O2 -MT libjwt_la-jwt-openssl.lo -MD -MP -MF .deps/libjwt_la-jwt-openssl.Tpo -c -o libjwt_la-jwt-openssl.lo `test -f 'jwt-openssl.c' || echo './'`jwt-openssl.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -Wall -I/usr/local/include -D_GNU_SOURCE -g -O2 -MT libjwt_la-jwt-openssl.lo -MD -MP -MF .deps/libjwt_la-jwt-openssl.Tpo -c jwt-openssl.c  -fPIC -DPIC -o .libs/libjwt_la-jwt-openssl.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -Wall -I/usr/local/include -D_GNU_SOURCE -g -O2 -MT libjwt_la-jwt-openssl.lo -MD -MP -MF .deps/libjwt_la-jwt-openssl.Tpo -c jwt-openssl.c -o libjwt_la-jwt-openssl.o >/dev/null 2>&1
mv -f .deps/libjwt_la-jwt-openssl.Tpo .deps/libjwt_la-jwt-openssl.Plo
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I/usr/local/include    -D_GNU_SOURCE -g -O2 -version-info 10:2:8    -no-undefined  -o libjwt.la -rpath /usr/local/lib libjwt_la-jwt.lo libjwt_la-base64.lo libjwt_la-jwt-openssl.lo  -L/usr/local/lib -ljansson -lssl -lcrypto
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libjwt_la-jwt.o .libs/libjwt_la-base64.o .libs/libjwt_la-jwt-openssl.o   -L/usr/local/lib /usr/local/lib/libjansson.so -lssl -lcrypto  -g -O2   -Wl,-soname -Wl,libjwt.so.2 -o .libs/libjwt.so.2.8.2
libtool: link: (cd ".libs" && rm -f "libjwt.so.2" && ln -s "libjwt.so.2.8.2" "libjwt.so.2")
libtool: link: (cd ".libs" && rm -f "libjwt.so" && ln -s "libjwt.so.2.8.2" "libjwt.so")
libtool: link: ar cr .libs/libjwt.a  libjwt_la-jwt.o libjwt_la-base64.o libjwt_la-jwt-openssl.o
libtool: link: ranlib .libs/libjwt.a
libtool: link: ( cd ".libs" && rm -f "libjwt.la" && ln -s "../libjwt.la" "libjwt.la" )
make[2]: Leaving directory '/root/vijay/jwt/libjwt/libjwt'
make[1]: Leaving directory '/root/vijay/jwt/libjwt/libjwt'
Making all in tests
make[1]: Entering directory '/root/vijay/jwt/libjwt/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/vijay/jwt/libjwt/tests'
Making all in dist
make[1]: Entering directory '/root/vijay/jwt/libjwt/dist'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/vijay/jwt/libjwt/dist'
Making all in examples
make[1]: Entering directory '/root/vijay/jwt/libjwt/examples'
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT main-gen.o -MD -MP -MF .deps/main-gen.Tpo -c -o main-gen.o main-gen.c
mv -f .deps/main-gen.Tpo .deps/main-gen.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwtgen main-gen.o -ljwt
libtool: link: gcc -Wall -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwtgen main-gen.o  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT main-auth.o -MD -MP -MF .deps/main-auth.Tpo -c -o main-auth.o main-auth.c
mv -f .deps/main-auth.Tpo .deps/main-auth.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwtauth main-auth.o -ljwt
libtool: link: gcc -Wall -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwtauth main-auth.o  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so
make[1]: Leaving directory '/root/vijay/jwt/libjwt/examples'
make[1]: Entering directory '/root/vijay/jwt/libjwt'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/root/vijay/jwt/libjwt

*******************************************
root@vj-ansible-node:~/vijay/jwt/libjwt# make check
Making check in include
make[1]: Entering directory '/root/vijay/jwt/libjwt/include'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/root/vijay/jwt/libjwt/include'
Making check in libjwt
make[1]: Entering directory '/root/vijay/jwt/libjwt/libjwt'
make[1]: Leaving directory '/root/vijay/jwt/libjwt/libjwt'
Making check in tests
make[1]: Entering directory '/root/vijay/jwt/libjwt/tests'
make  jwt_new jwt_grant jwt_header jwt_dump jwt_encode jwt_rsa jwt_ec jwt_validate
make[2]: Entering directory '/root/vijay/jwt/libjwt/tests'
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_new.o -MD -MP -MF .deps/jwt_new.Tpo -c -o jwt_new.o jwt_new.c
mv -f .deps/jwt_new.Tpo .deps/jwt_new.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwt_new jwt_new.o -ljwt -lcheck_pic -pthread -lrt -lm -lsubunit
libtool: link: gcc -Wall -pthread -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwt_new jwt_new.o -pthread  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so -lcheck_pic -lrt -lm -lsubunit -pthread
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_grant.o -MD -MP -MF .deps/jwt_grant.Tpo -c -o jwt_grant.o jwt_grant.c
mv -f .deps/jwt_grant.Tpo .deps/jwt_grant.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwt_grant jwt_grant.o -ljwt -lcheck_pic -pthread -lrt -lm -lsubunit
libtool: link: gcc -Wall -pthread -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwt_grant jwt_grant.o -pthread  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so -lcheck_pic -lrt -lm -lsubunit -pthread
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_header.o -MD -MP -MF .deps/jwt_header.Tpo -c -o jwt_header.o jwt_header.c
mv -f .deps/jwt_header.Tpo .deps/jwt_header.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwt_header jwt_header.o -ljwt -lcheck_pic -pthread -lrt -lm -lsubunit
libtool: link: gcc -Wall -pthread -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwt_header jwt_header.o -pthread  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so -lcheck_pic -lrt -lm -lsubunit -pthread
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_dump.o -MD -MP -MF .deps/jwt_dump.Tpo -c -o jwt_dump.o jwt_dump.c
mv -f .deps/jwt_dump.Tpo .deps/jwt_dump.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwt_dump jwt_dump.o -ljwt -lcheck_pic -pthread -lrt -lm -lsubunit
libtool: link: gcc -Wall -pthread -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwt_dump jwt_dump.o -pthread  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so -lcheck_pic -lrt -lm -lsubunit -pthread
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_encode.o -MD -MP -MF .deps/jwt_encode.Tpo -c -o jwt_encode.o jwt_encode.c
mv -f .deps/jwt_encode.Tpo .deps/jwt_encode.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwt_encode jwt_encode.o -ljwt -lcheck_pic -pthread -lrt -lm -lsubunit
libtool: link: gcc -Wall -pthread -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwt_encode jwt_encode.o -pthread  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so -lcheck_pic -lrt -lm -lsubunit -pthread
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_rsa.o -MD -MP -MF .deps/jwt_rsa.Tpo -c -o jwt_rsa.o jwt_rsa.c
mv -f .deps/jwt_rsa.Tpo .deps/jwt_rsa.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwt_rsa jwt_rsa.o -ljwt -lcheck_pic -pthread -lrt -lm -lsubunit
libtool: link: gcc -Wall -pthread -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwt_rsa jwt_rsa.o -pthread  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so -lcheck_pic -lrt -lm -lsubunit -pthread
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_ec.o -MD -MP -MF .deps/jwt_ec.Tpo -c -o jwt_ec.o jwt_ec.c
mv -f .deps/jwt_ec.Tpo .deps/jwt_ec.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwt_ec jwt_ec.o -ljwt -lcheck_pic -pthread -lrt -lm -lsubunit
libtool: link: gcc -Wall -pthread -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwt_ec jwt_ec.o -pthread  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so -lcheck_pic -lrt -lm -lsubunit -pthread
gcc -DHAVE_CONFIG_H -I. -I../libjwt  -I../include  -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -MT jwt_validate.o -MD -MP -MF .deps/jwt_validate.Tpo -c -o jwt_validate.o jwt_validate.c
mv -f .deps/jwt_validate.Tpo .deps/jwt_validate.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -pthread -DKEYDIR="\"./keys\"" -D_GNU_SOURCE -g -O2 -L../libjwt  -o jwt_validate jwt_validate.o -ljwt -lcheck_pic -pthread -lrt -lm -lsubunit
libtool: link: gcc -Wall -pthread -DKEYDIR=\"./keys\" -D_GNU_SOURCE -g -O2 -o .libs/jwt_validate jwt_validate.o -pthread  -L../libjwt /root/vijay/jwt/libjwt/libjwt/.libs/libjwt.so -lcheck_pic -lrt -lm -lsubunit -pthread
make[2]: Leaving directory '/root/vijay/jwt/libjwt/tests'
make  check-TESTS
make[2]: Entering directory '/root/vijay/jwt/libjwt/tests'
make[3]: Entering directory '/root/vijay/jwt/libjwt/tests'
PASS: jwt_new
PASS: jwt_grant
PASS: jwt_header
PASS: jwt_dump
PASS: jwt_encode
PASS: jwt_rsa
PASS: jwt_ec
PASS: jwt_validate
============================================================================
Testsuite summary for libjwt 1.15.2
============================================================================
# TOTAL: 8
# PASS:  8
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/root/vijay/jwt/libjwt/tests'
make[2]: Leaving directory '/root/vijay/jwt/libjwt/tests'
make[1]: Leaving directory '/root/vijay/jwt/libjwt/tests'
Making check in dist
make[1]: Entering directory '/root/vijay/jwt/libjwt/dist'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/root/vijay/jwt/libjwt/dist'
Making check in examples
make[1]: Entering directory '/root/vijay/jwt/libjwt/examples'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/root/vijay/jwt/libjwt/examples'
make[1]: Entering directory '/root/vijay/jwt/libjwt'
make[1]: Nothing to be done for 'check-am'.
make[1]: Leaving directory '/root/vijay/jwt/libjwt'

**Comment by benmcollins** [comment]
You have to run `sudo make install`
