### ISSUE TITLE
missing `libjwt-1.15.3.tar.gz` for 1.15.3 release

### ISSUE THREAD

**Issue by chenrui333** [benmcollins/libjwt#173]
👋 it looks like for the 1.15.3 release, the tarball file (`libjwt-1.15.3.tar.gz`) is not present, and also the release did not get marked as latest release either. Create this issue to raise some awareness. Thanks!

**Comment by benmcollins** [comment]
An oversight on my part. I'll get this done today. Thanks for reporting!
