### ISSUE TITLE
JWT: jwt_encode_str() function return only three characters.

### ISSUE THREAD

**Issue by muramasaz** [benmcollins/libjwt#174]
Why is jwt_encode_str() function return only three characters ?

**Comment by benmcollins** [comment]
I would need to see an example of how you’re using it in order to answer this question.

**Comment by muramasaz** [comment]
Here is the function that I use for gen JWT.

int generateJWT(char *szJWTOut) {
//	int fp = 0;
	int ret = 0;
//	int keycode = 0;
	jwt_t *jwt;
//	jwt_alg_t opt_alg = JWT_ALG_RS256;
	jwt_alg_t opt_alg = JWT_ALG_RS512;
	char uuid[LENGTH_UUID+1] = {0};
	char szKey[8192] = {0};
	char szEdcSerial[1280] = {0};
	int nFileSize = 0;
	int nReJWT = 0;
	char *out = NULL;

//	PubGetPosInfo(HARDWARE_GET_POS_USN, szEdcSerial);
	NDK_SysGetPosInfo(HARDWARE_GET_POS_USN , NULL, szEdcSerial);
	TRACE(("generateJWT_EDC Serial: %s", szEdcSerial));
	
	// SetVarIsUATInt(2); // hard code for testing.
	
	if(GetVarIsUATInt() == 1) {
		NDK_FsFileSize(JWT_RSA_PRIVATE_KEY_SIT, &nFileSize);
		ret = NDK_FsOpen(JWT_RSA_PRIVATE_KEY_SIT, "r");
	} else if(GetVarIsUATInt() == 2)
	{
		NDK_FsFileSize(JWT_RSA_PRIVATE_KEY_UAT, &nFileSize);
		ret = NDK_FsOpen(JWT_RSA_PRIVATE_KEY_UAT, "r");
	} 
	else {
		NDK_FsFileSize(JWT_RSA_PRIVATE_KEY_PROD, &nFileSize);
		ret = NDK_FsOpen(JWT_RSA_PRIVATE_KEY_PROD, "r");
	}
	if (ret <= 0)
	{
		TRACE(("generateJWT_Open file error;"));
		return APP_FAIL;
	}
	NDK_FsRead(ret, szKey, (uint)nFileSize);
	NDK_FsClose(ret);

	// TRACE(("generateJWT_szKey: [%d]", nFileSize));
	time_t iat = time(NULL);
	time_t exp = iat + (60 * UOB_EKYC_JWT_TIME_OUT);
	TRACE(("iat: [%lld]", iat));
	TRACE(("exp: [%lld]", exp));

	ret = jwt_new(&jwt);
	if (ret != 0 || jwt == NULL)
	{
		jwt_free(jwt);

		NDK_ScrClrs();
		TRACE(("generateJWT_Invalid JWT"));
		NDK_ScrRefresh();
		NDK_SysMsDelay(3000);

//		continue;
		return APP_FAIL;
	}

	jwt_add_grant(jwt, "sub", szEdcSerial);
	jwt_add_grant(jwt, "auth", "EDC-VERIFY");
	jwt_add_grant_int(jwt, "iat", iat);
	jwt_add_grant_int(jwt, "exp", exp);
	generate_uuid(uuid);
	jwt_add_grant(jwt, "jti", uuid);
	// TRACE(("generateJWT_UUID: [%s]", uuid));

	ret = jwt_set_alg(jwt, opt_alg, (unsigned char *)szKey, nFileSize);
	// TRACE(("generateJWT_jwt_set_alg: [%d]", ret));
	if (ret < 0)
	{
		jwt_free(jwt);
		NDK_ScrClrs();
		TRACE(("jwt incorrect algorithm"));
		NDK_ScrRefresh();
		NDK_SysMsDelay(3000);
//		continue;
		return APP_FAIL;
	}

	/* get json web token */
	out = jwt_encode_str(jwt);
	jwt_free_str(out);
	jwt_free(jwt);

	if(out == NULL) {
		return APP_FAIL;
	} else if(strlen(out) <= 0) {
		return APP_FAIL;
	}else {
		if(IsJwtFormat(out) == APP_FAIL) {
			return APP_FAIL;
		}
	}

	memcpy(szJWTOut, out, strlen(out));
//	NDK_SysMsDelay(3000);

	return APP_SUCC;
}

And here is the result :
![image](https://github.com/benmcollins/libjwt/assets/10528876/29adea75-4dae-4d98-91de-f83235a0119a)

**Comment by benmcollins** [comment]
/* get json web token */
        out = jwt_encode_str(jwt);
        jwt_free_str(out);
        jwt_free(jwt);

You create the string, then you free the buffer containing the string. And then you attempt to use `out` which is now pointing to free'd memory. Do not free that string until after you are done with it.

**Comment by muramasaz** [comment]
Thank you.
