### ISSUE TITLE
Correct package on Debian 12

### ISSUE THREAD

**Issue by bschooly** [benmcollins/libjwt#178]
I'm porting an app from centos to debian (wonder why? :) 

In centos I have 

Name        : libjwt
Arch        : x86_64
Version     : 1.12.1
Release     : 7.el7
Size        : 51 k
Repo        : installed
From repo   : epel
Summary     : A Javascript Web Token library in C
URL         : https://github.com/benmcollins/libjwt
License     : MPLv2.0
Description : A Javascript Web Token library in C

In Debian, I can't seem to find the right package. Tried them all. I get errors like:

login.c:800:9: error: unknown type name âjwt_valid_tâ; did you mean âjwt_alg_tâ?
  800 |         jwt_valid_t *jwt_valid;
      |         ^~~~~~~~~~~
      |         jwt_alg_t
login.c:901:15: error: implicit declaration of function âjwt_valid_newâ; did you mean âsk_void_newâ? [-Werror=implicit-function-declaration]
  901 |         ret = jwt_valid_new(&jwt_valid, opt_alg);

Does anyone know which debian package matches what I have on centos?

This is Debian 12 and here is what is available:

root@debian:/usr/local/billmax/src/bin/edge# apt-cache search  libjwt
libjwt-dev - C library to handle JWT (JSON Web Token) - development
libjwt-gnutls-dev - Development files for libjwt - GnuTLS flavour
libjwt-gnutls0 - C library to handle JWT (JSON Web Token) - GnuTLS flavour
libjwt0 - C library to handle JWT (JSON Web Token)

**Comment by benmcollins** [comment]
It depends on what version of Debian you're running, but try:

    dpkg -l | grep libjwt

or

    apt-cache show libjwt0

See what versions are installed. Unless you're running the bleeding edge development version, it won't be the latest LibJWT.

**Comment by bschooly** [comment]
root@debian:/usr/local/billmax/src/bin/edge# dpkg -l | grep libjwt
ii  libjwt-dev:amd64                1.10.2-1+b1                    amd64        C library to handle JWT (JSON Web Token) - development
ii  libjwt0:amd64                   1.10.2-1+b1                    amd64        C library to handle JWT (JSON Web Token)

root@debian:/usr/local/billmax/src/bin/edge# apt-cache search  libjwt
libjwt-dev - C library to handle JWT (JSON Web Token) - development
libjwt-gnutls-dev - Development files for libjwt - GnuTLS flavour
libjwt-gnutls0 - C library to handle JWT (JSON Web Token) - GnuTLS flavour
libjwt0 - C library to handle JWT (JSON Web Token)

So I note on centos I got 1.12.1 installed. Is there this much difference between 1.10,2 and 1.12.1?

**Comment by benmcollins** [comment]
Both of those are pretty old. Looks like Debian only has 1.10.2 across all of their dists right now, and since Ubuntu pulls from Debian, they are just as outdated. You'll need to build locally to get the latest version.

**Comment by bschooly** [comment]
Okay, tried that.... Following readme. 

## Build Instructions

**With GNU Make:** Use ``autoreconf -i`` to create project files and run ``./configure``.
- ``make all``: build library.
- ``make check``: build and run test suite.
- See INSTALL file for more details on GNU Auto tools and GNU Make.
- Use the ``--without-openssl`` with ``./configure`` to use GnuTLS.

The build attempt:

===> libjwt-1.15.3
configure.ac:3: installing './install-sh'
configure.ac:3: installing './missing'
examples/Makefile.am: installing './depcomp'
/usr/share/automake-1.16/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.16/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.16/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.16/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.16/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.16/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
examples/Makefile.am: error: C source seen but 'CC' is undefined
examples/Makefile.am:   The usual way to define 'CC' is to add 'AC_PROG_CC'
examples/Makefile.am:   to 'configure.ac' and run 'autoconf' again.
libjwt/Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
libjwt/Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libjwt/Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libjwt/Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
libjwt/Makefile.am:3:   its definition is in aclocal's search path.
libjwt/Makefile.am: error: C source seen but 'CC' is undefined
libjwt/Makefile.am:   The usual way to define 'CC' is to add 'AC_PROG_CC'
libjwt/Makefile.am:   to 'configure.ac' and run 'autoconf' again.
tests/Makefile.am: error: C source seen but 'CC' is undefined
tests/Makefile.am:   The usual way to define 'CC' is to add 'AC_PROG_CC'
tests/Makefile.am:   to 'configure.ac' and run 'autoconf' again.
parallel-tests: installing './test-driver'
autoreconf: error: automake failed with exit status: 1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 2609: syntax error near unexpected token `2.2'
./configure: line 2609: `LT_PREREQ(2.2)'
gmake[1]: *** No rule to make target 'install'.  Stop.
gmake: *** [../subdir.mk:23: install] Error 1

Thoughts?

**Comment by bschooly** [comment]
Closer 👍 

===> libjwt-1.15.3
configure.ac: warning: missing AC_CHECK_FUNCS([memchr]) wanted by: libjwt/jwt-wincrypt.c:56
configure.ac: warning: missing AC_CHECK_FUNCS([memset]) wanted by: libjwt/jwt-gnutls.c:230
configure.ac: warning: missing AC_CHECK_FUNCS([strdup]) wanted by: examples/main-auth.c:82
configure.ac: warning: missing AC_FUNC_ALLOCA wanted by: libjwt/jwt-gnutls.c:88
configure.ac: warning: missing AC_FUNC_MALLOC wanted by: tests/jwt_dump.c:15
configure.ac: warning: missing AC_FUNC_REALLOC wanted by: tests/jwt_dump.c:25
configure.ac: warning: missing AC_PROG_CC wanted by: tests/jwt_header.c
configure.ac: warning: missing AC_TYPE_SIZE_T wanted by: tests/jwt_ec.c:34
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:5: installing './compile'
configure.ac:5: installing './config.guess'
configure.ac:5: installing './config.sub'
configure.ac:3: installing './install-sh'
configure.ac:3: installing './missing'
examples/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for file... file
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
./configure: line 12697: syntax error near unexpected token `OPENSSL,'
./configure: line 12697: `      PKG_CHECK_MODULES(OPENSSL, openssl >= 0.9.8)'

**Comment by bschooly** [comment]
Okay. got it. I neede libtool, pkg-config then libjansson-dev

Thanks.
