### ISSUE TITLE
Upgrade `m4/doxygen.m4` to `ax_prog_doxygen.m4` from GNU Autoconf Archive?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [benmcollins/libjwt#181]
Looks like a more recent version and maintained of [`m4/doxygen.m4`](https://github.com/benmcollins/libjwt/blob/master/m4/doxygen.m4):

https://www.gnu.org/software/autoconf-archive/ax_prog_doxygen.html

**Comment by benmcollins** [comment]
Is there something not working with the current version? Does it require updating `doxygen.cfg` and `doxygen.mk`?

**Comment by DimitriPapadopoulos** [comment]
The current version appears to be working fine. I was just wondering where it comes from, I could find only the GNU Autoconf Archive version.

Besides, I wouldn't recommend upgrading to a very recent version, my experience is that the GNU Autonconf Archive has evolved in the last few years, adding a bunch of dependencies to each M4 file.
