### ISSUE TITLE
Error parsing fractional values in JWT exp

### ISSUE THREAD

**Issue by max-lt** [benmcollins/libjwt#188]
Hello, I am maintaining a nginx module using libjwt, someone reported that [the exp value is not parsed correctly](https://github.com/max-lt/nginx-jwt-module/discussions/33) when using a fractional (for example `"exp": 1698742245.336421`).

Is that intended ? 

[This issue](https://github.com/OpenIDC/mod_auth_openidc/issues/187) seems to conclude that "non-integer values can be represented" as stated in https://tools.ietf.org/html/rfc7519#section-4.1.4 / https://www.rfc-editor.org/rfc/rfc7519#section-2

**Comment by benmcollins** [comment]
I'll look into fixing this. I can't imagine why someone would need more precision for `exp` than the processing speed of parsing and comparing the values, but I'll concede it isn't difficult to get it to work 😄

**Comment by max-lt** [comment]
Thank you. I totally missed that case either 😁

**Comment by offtza01** [comment]
Gentlemans, i didn't seen this on first look, I used stock php, symfony class to generate token, so please don't kill me for that ;]
