### ISSUE TITLE
Issue seen while using jwt_decode api

### ISSUE THREAD

**Issue by M-Behere** [benmcollins/libjwt#197]
Hi @benmcollins,

I'm observing a issue while using jwt_decode funtion. While using a valid jwt string of size n, this function returns 0 as expected. But when introduced a random character at the end of jwt string, this function still returns 0. (Expect it to return a non-zero value for invalid string).
When introduced 2 random character at the end of jwt string, this function returns non-zero value. (Expected result)
I suspect that (nprbytes ==1) condition inside jwt_Bse64decode is not handled which is causing this error case to pass.

 
![image](https://github.com/benmcollins/libjwt/assets/37775225/d53f355d-8668-40c8-9e67-3be76854afec)

Can you give some inputs on how this case can be handled?

**Comment by benmcollins** [comment]
I can see where this ignores invalid trailing data. Not the cleanest handling in this case, and it can be cleaned up to not ignore that.

Thinking into it, does it pose a security risk? I can't imagine a *normal* case where it would, but then people do all kinds of weird things and there may be assumptions where this could cause an expected issue.

How does the checker on JWT.io handle this case?

**Comment by M-Behere** [comment]
JWT.io throws signature error for 1 extra character

**Comment by benmcollins** [comment]
Pushed a fix to main code and added a test case to ensure no regressions.

Thanks!
