### ISSUE TITLE
String format is different for a property between jwt_get_grants_json and jwt_get_grant

### ISSUE THREAD

**Issue by psuresh1983** [benmcollins/libjwt#198]
When i try read below data as json with jwt_get_grants_json then it escapes \n with another \
"pubkey":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsVxVj1TuPN4otznshtFyCIns"

But when I try to read the grant with "pubkey" using jwt_get_grant then the correct format is returned.

**Comment by benmcollins** [comment]
JSON formatting will escape characters. This is expected, I believe.

**Comment by psuresh1983** [comment]
The data what i had sent over network is of this format in json. The recipient has received and signed this data. No escape character added to the signed data so far in the step. But when im trying to fetch using jwt_get_grants_json, its adding extra escape character which was not expected.

**Comment by benmcollins** [comment]
I'd have to dig into the code to see if there is an error in LibJWT or Jannson.

**Comment by benmcollins** [comment]
Can you provide the JWT in question?

**Comment by benmcollins** [comment]
So here's the long and short of it. The function `jwt_get_grants_json()` uses `JSON_ENCODE_ANY` and this is a side effect of that. I can't find a clean way to work around this. So either use `jwt_get_grant()` or get the entire JSON object with `jwt_get_grants_json()` using `NULL` as the key, and then parse the entire JSON string outside of LibJWT.
