### ISSUE TITLE
Memory issue in jwt_encode_str

### ISSUE THREAD

**Issue by NitinKMathur** [benmcollins/libjwt#2]
In statement:
`str = malloc(len);`

memory is not allocated for NULL char.

**Comment by benmcollins** [comment]
I don't see how there can be an empty buffer returned from `BIO_pending()` (which is filled from `jwt_encode_bio()`).

Did you have a case where you see this happening?

**Comment by NitinKMathur** [comment]
Yes, I was getting error white using jwt_encode_str(). What my doubt is, shouldn't it be
 str = malloc(len+1);
 instead of 
str = malloc(len);? 
Because at the end you are doing
str[len] = '\0';
but memory is not allocated for '\0'.
