### ISSUE TITLE
(Master) -version-info missing during make step when compiling from source

### ISSUE THREAD

**Issue by stuffyAI** [benmcollins/libjwt#204]
I receive the following error during the second make step:

`/bin/sh ../libtool  --tag=CC   --mode=link gcc  -DOPENSSL_LOAD_CONF   -D_GNU_SOURCE -g -O2 -version-info      -no-undefined  -o libjwt.la -rpath /sven/slurmtest1/workspace/usr/local/slurm/24.11/tmp_install_files/jwt/fin/lib64 libjwt_la-jwt.lo libjwt_la-jwks.lo libjwt_la-base64.lo libjwt_la-jwt-openssl.lo libjwt_la-jwks-openssl.lo   -ljansson -lssl -lcrypto   
Putting child 0x55d343fe9880 (libjwt.la) PID 24686 on the chain.
Live child 0x55d343fe9880 (libjwt.la) PID 24686 
libtool:   error: CURRENT '-no-undefined' must be a nonnegative integer
libtool:   error: '-no-undefined' is not valid version information`

which happens in the make step in relative dir ./build/libjwt .

Peeking at the makefile in that directory I see that a few version variables are not set, such as libjwt_version_info, but those don't seem to matter.

I have followed the build steps, latest version of dependencies and I also tried an OpenSSL 1.1.1 version in case the issue lies in their newest version libraries, no success.

**Comment by stuffyAI** [comment]
I am able to successfully make by manually appending the version number to the `libjwt_la_LDFLAGS` variable in said Makefile, but I have no glue why it could be missing there.

**Comment by benmcollins** [comment]
Hi. Can you send the full text of your steps from checkout to this? As you can see in the Travis-CI logs, the latest version definitely builds.

**Comment by stuffyAI** [comment]
Aight.
Due to circumstances I have to compile jwt on a machine without internet, which is why I manually move the repo there after cloning it via --recursive.

`cd building-dir/jwt
cp -r [repo location] libjwt
cd libjwt
autoreconf --force --install
mkdir -p ./../build
cd ../build
../libjwt/configure --prefix=[desired path] //optionally --with-openssl and --with-PACKAGE=[path to openssl1.1.1] for testing that specific version
make
make install`

**Comment by benmcollins** [comment]
This is the magic in `configure.ac`:

```
dnl This sets it for Autconf and CMake
m4_define([major_version], [2])
m4_define([minor_version], [1])
m4_define([micro_version], [0])
m4_define([libjwt_version], [major_version.minor_version.micro_version])

dnl SONAME History
dnl v1.12.1      0 => 1
dnl v1.15.0      1 => 2
dnl http://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
m4_define([so_current],         [13])
m4_define([so_revision],        [1])
m4_define([so_age],             [11])
m4_define([libjwt_version_info], [so_current:so_revision:so_age])

m4_define([libjwt_project], [LibJWT])

AC_PREREQ([2.61])
AC_INIT([libjwt_project],[libjwt_version],[https://github.com/benmcollins/libjwt/issues])
...
AC_SUBST([libjwt_version_info], [libjwt_version_info])
```

After running ``autoreconf -fi`` I can open edit the ``configure`` script and find this at the top:

```
# Guess values for system-dependent variables and create Makefiles.
# Generated by GNU Autoconf 2.72 for LibJWT 2.1.0.```
```

This a little further down:

```
# Identity of this package.
PACKAGE_NAME='LibJWT'
PACKAGE_TARNAME='libjwt'
PACKAGE_VERSION='2.1.0'
PACKAGE_STRING='LibJWT 2.1.0'
PACKAGE_BUGREPORT='https://github.com/benmcollins/libjwt/issues'
PACKAGE_URL=''
```

And this even further down:

```
libjwt_version_info=13:1:11
```

Can you check your `configure` script after running ``autoreconf``?

**Comment by benmcollins** [comment]
Here's the link command I get when building:

```
/bin/sh ../libtool  --tag=CC   --mode=link gcc -I/opt/homebrew/Cellar/jansson/2.14/include -I/opt/homebrew/Cellar/openssl@3/3.4.0/include -I/opt/homebrew/Cellar/gnutls/3.8.4/include -I/opt/homebrew/Cellar/nettle/3.10/include -I/opt/homebrew/Cellar/libtasn1/4.19.0/include -I/opt/homebrew/Cellar/libidn2/2.3.7/include -I/opt/homebrew/Cellar/p11-kit/0.25.5/include/p11-kit-1  -D_GNU_SOURCE -g -O2 -version-info 13:1:11     -no-undefined  -o libjwt.la -rpath /usr/local/lib libjwt_la-jwt.lo libjwt_la-jwks.lo libjwt_la-base64.lo libjwt_la-jwt-openssl.lo libjwt_la-jwks-openssl.lo libjwt_la-jwt-gnutls.lo libjwt_la-jwks-gnutls.lo  -L/opt/homebrew/Cellar/jansson/2.14/lib -ljansson -L/opt/homebrew/Cellar/openssl@3/3.4.0/lib -lssl -lcrypto -L/opt/homebrew/Cellar/gnutls/3.8.4/lib -lgnutls```

**Comment by stuffyAI** [comment]
I cleared the build folder and restarted up to autoreconf, my configure file has the following changes:

`# Generated by GNU Autoconf 2.69 for LibJWT 2.1.0.`
gnu autoconf version is 3 minors back

`PACKAGE_TARNAME='LibJWT'`
my version has capitalization for the tar name, probably irrelevant

I have no `libjwt_version_info=` at all in my file, the only similar thing is a collection(?) called "ac_subst_vars" that looks like

> ac_subst_vars='am__EXEEXT_FALSE
am__EXEEXT_TRUE
...
AM_CFLAGS
libjwt_version_info
CPP
...
enable_doxygen_ps
enable_doxygen_pdf
'

autoreconf does not show anything suspicious, even in verbose mode

**Comment by benmcollins** [comment]
I'm wondering if the versioning is the problem. I'm using autoconf 2.71 and 2.72 on my local systems and on the CI pipeline. Let me kick off a build on an older linux and see what happens.

However, the `PACKAGE_TARNAME` is suspect. In autoconf's `general.m4` there's this:

```
m4_define_default([AC_PACKAGE_TARNAME],
  m4_ifnblank([$4], [[$4]],
    [m4_quote(m4_bpatsubst(m4_tolower(m4_bpatsubst([$1], [^GNU ], [])),
      [[^_abcdefghijklmnopqrstuvwxyz0123456789]], [-]))]))
```

By default it should be the lowercase of the PACKAGE_NAME (`m4_tolower`).

**Comment by benmcollins** [comment]
Current head seems to have this fixed. Please retest.

**Comment by stuffyAI** [comment]
I have pulled the latest main and still get PACKAGE_TARNAME='LibJWT' with capitalization, and version in resulting makefile is missing.

However, I see now that building this library has switched to cmake fully, which seems to work, but now I do not know how to specify install directory, where static and dynamic libraries are found, and how to specify which libraries to link against when they are in unusual places. Any pointers?
