### ISSUE TITLE
Setting algorithm to none, creates invalid output when encoding

### ISSUE THREAD

**Issue by rlaveaux** [benmcollins/libjwt#22]
When you create a JWT with the algorithm set to none, then invalid output is created during encoding.

Compare the following two tokens:

1. Algorithm set to HS256: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ3d3cucGx1Z2dlcnMubmwiLCJleHAiOjE0Nzc1MTQ3NTEsInN1YiI6IlBsdWdnZXJzIFNvZnR3YXJlIn0.lHIcuX82YFcTlv__JQPhyg_vcMm5X8mPkWA4WWBqLvk
2. Same grants, with algorithm set to none:
 eyJhbGciOiJub25lIn0=.eyJhdWQiOiJ3d3cucGx1Z2dlcnMubmwiLCJleHAiOjE0Nzc1MTQ4MTIsInN1YiI6IlBsdWdnZXJzIFNvZnR3YXJlIn.

Please notice the following difference:
The body part should be the same, but with token # 2 the last character (0) is missing.

While debugging I can see it getting truncated in the function "base64uri_encode". The reason why it is being truncated is because there is an "=" character in the header part of the token.

So the cause of this problem is that the "=" character in the header does not get truncated.

**Comment by benmcollins** [comment]
Thanks. This was a great catch. Fixed and pushed out v1.6.0.
