### ISSUE TITLE
Unknown CMake command add_compile_options

### ISSUE THREAD

**Issue by fitzyjoe** [benmcollins/libjwt#26]
When I try to build I get this error:

Unknown CMake command "add_compile_options".

Apparently that's a feature of CMake 2.8.12 and later and CMakeLists.txt requires 2.8

cmake_minimum_required(VERSION 2.8)

I tried kicking it up to 2.8.12, but I only have 2.8.11... I'm on CentOS.  Trying to figure out why I'm not getting this update.

**Comment by benmcollins** [comment]
I strongly suggest using auto tools (`./configure`). I didn't create the CMake build and it's mostly unmaintained. I've thought about removing it because things like this aren't being tested.

**Comment by benmcollins** [comment]
You can try changing the add_compile_options line to:

    add_definitions(-DKEYDIR="${PROJECT_SOURCE_DIR}/tests/keys")

That might work. Please report if it does.

**Comment by fitzyjoe** [comment]
I switched to using ./configure and that worked better.  I'm eventually building on CentOS (working now), but I'm doing local development on OSX (broken).  I wanted to let you know that I ran into this problem with your latest commit.

`joefitz@Plum:~/Documents/Projects/Tesla/git/libjwt $ make all
Making all in include
make[1]: Nothing to be done for `all'.
Making all in libjwt
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I../include   -Wall  -I/usr/local/include   -g -O2 -MT libjwt_la-jwt.lo -MD -MP -MF .deps/libjwt_la-jwt.Tpo -c -o libjwt_la-jwt.lo `test -f 'jwt.c' || echo './'`jwt.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -Wall -I/usr/local/include -g -O2 -MT libjwt_la-jwt.lo -MD -MP -MF .deps/libjwt_la-jwt.Tpo -c jwt.c  -fno-common -DPIC -o .libs/libjwt_la-jwt.o
jwt.c:899:24: error: only weak aliases are supported on darwin
        __attribute__ ((weak, alias ("jwt_del_grants")));
                              ^
1 error generated.
make[2]: *** [libjwt_la-jwt.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1`

**Comment by benmcollins** [comment]
Thanks. This should be fixed by commit 0da9f99afd38b4e0b06503be5487bb67d73fbf51

**Comment by fitzyjoe** [comment]
Thanks!  Build works on OSX.
