### ISSUE TITLE
LibJWT Needs a logo. Submit suggestions here...

### ISSUE THREAD

**Issue by benmcollins** [benmcollins/libjwt#27]

**Comment by fitzyjoe** [comment]
![libjwt](https://cloud.githubusercontent.com/assets/6208666/20785159/bb397eda-b76c-11e6-8936-584532593a7b.png)
Modeled after a NYC subway token... like this one: http://metrocard.levradin.com/wp-content/uploads/sites/2/2013/10/cuty.jpg
This is the Illustrator file in case someone wants to improve this.
[LibJWT.ai.zip](https://github.com/benmcollins/libjwt/files/623911/LibJWT.ai.zip)

**Comment by benmcollins** [comment]
@fitzyjoe Awesome. Once we get a few submissions, we'll get a vote going. Thanks for the contribution!

**Comment by fitzyjoe** [comment]
Here's another option... simpler.
![libjwt-2](https://user-images.githubusercontent.com/6208666/27286727-33754906-54cf-11e7-90f7-d0772c99b2c0.png)

This is the Illustrator file 
[libjwt-2.ai.zip](https://github.com/benmcollins/libjwt/files/1084997/libjwt-2.ai.zip)

**Comment by benmcollins** [comment]
I don't have the right tools to export this. Can I get it in SVG format? (the first one)

Thanks

**Comment by fitzyjoe** [comment]
Here's an SVG version.

[LibJWT.svg.zip](https://github.com/benmcollins/libjwt/files/1518242/LibJWT.svg.zip)

**Comment by fitzyjoe** [comment]
Hmm... it's rendering the "LIB" a little crooked.  Let me have another look.  I'm exporting from Illustrator.

**Comment by fitzyjoe** [comment]
Browser renders it well... it's just Illustrator that renders it crooked.  So, should be good.

**Comment by benmcollins** [comment]
rsvp-convert and Boxy both have the same issue:

![libjwt-64x64](https://user-images.githubusercontent.com/320303/33439413-5a58fa0a-d5bb-11e7-9047-889e23e62e99.png)

**Comment by benmcollins** [comment]
Found an online tool to convert the AI to SVG without the issue.
