### ISSUE TITLE
ES384 verification

### ISSUE THREAD

**Issue by iwanbk** [benmcollins/libjwt#28]
Hi,

Does ES384  verification already implemented?

I've read the code, and think that it should be implemented.

I asked this because:
- in jwt.io web page, es384 is not supported
- token & key which worked with PyJWT, not worked with this library.

more details about the issue:
- if i commented the code that do verification, decoding work properly
- verification failed at https://github.com/benmcollins/libjwt/blob/bb036db45fa4b340f2c3e1ea0abd0b2e5d90e836/libjwt/jwt.c#L565-L566

Let me know if you need more info about the issue

**Comment by benmcollins** [comment]
jwt.io is pending my pull request to update the ES/HS support.

I'd have to see your code for how you're verifying the JWT with this library. Are you able to supply the public key and the ES384 signed JWT you are verifying?

**Comment by iwanbk** [comment]
@benmcollins Thanks for your  response.

I just realised that it use ECDSA while your lib seems only support RSA.

Let me know if it also support ECDSA, i'll supply the key & jwt token.

**Comment by benmcollins** [comment]
It supports ECDSA and RSA both.

**Comment by iwanbk** [comment]
you can find all in https://gist.github.com/iwanbk/77794a7b8d6acf7f5ff392b808140eb5.
thanks for your help

**Comment by iwanbk** [comment]
i also just found out that PyJWT unable to verify es384, i used it the wrong way.

**Comment by benmcollins** [comment]
Most likely you are generating this JWT incorrectly then. Do you have the code used to create it LibJWT has ES256/384/512 tests that verify it can correctly decode and verify ES tokens, so the issue would appear to be that your JWT is not correct.

**Comment by benmcollins** [comment]
I was actually able to verify the signature using PyJWT:

    $ jwt --key="`cat ec.pub`" `cat jwt.token`
    {"username": "ibk", "aud": ["fj_3owjPslA4_50v6uLc0pAfLQeI"], "globalid": "fj_3owjPslA4_50v6uLc0pAfLQeI", "iss": "itsyouonline", "exp": 1479398132, "scope": ["user:memberof:goraml"]}

I'm going to do some cross comparison between PyJWT and LibJWT and see where the discrepancy is.

**Comment by benmcollins** [comment]
I've validated that ruby-jwt and python-jwt can sign/verify across each other, so something is definitely wrong with the LibJWT implementation. I'm tracking it down now.

**Comment by iwanbk** [comment]
```
I was actually able to verify the signature using PyJWT:
```
I don't know how the command line work because i use the library.

Worked:
```
return jwt.decode(token, iyo_pub_key, verify=False)
```

Not worked:
```
return jwt.decode(token, iyo_pub_key)
```
Got `jwt.exceptions.InvalidAlgorithmError: Algorithm not supported`

**Comment by iwanbk** [comment]
```
 Do you have the code used to create it? 
```
It is a Go code developed by someone else, i didn't check it because i assume that it works properly.

i'm going to check it also.

**Comment by iwanbk** [comment]
FYI, python-jose gave me this error message
```
"jose.exceptions.JWTClaimsError: Invalid audience"
```

**Comment by benmcollins** [comment]
I think I've found the issue. The output of the EVP Digest routines is the DER encoding and what we need is to store the raw R/S values for the signature. I'm working on a fix...

**Comment by benmcollins** [comment]
I had to force PyJWT to ignore audience for the purpose of just validating the signature.

**Comment by benmcollins** [comment]
I tested this fix against your JWT and EC public key and it verifies properly now.

**Comment by iwanbk** [comment]
thanks!
