### ISSUE TITLE
I'm not 100% sure, but IMHO libjwt library has the vulnerability described in JWT.io !

### ISSUE THREAD

**Issue by ghe0Rghe** [benmcollins/libjwt#33]
Hi there, 

please take a look at this post: https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

I suspect that the jwt_decode function is using the alg from JWT head and does not validate "alg" value against algorithm of the KEY.  So as described in the blog-post if the SERVER is using RS256 then the attacker can forge valid Tokens with HS256 using publicly available RS256 public key.  

Have  a good day,
Gheorghe

**Comment by benmcollins** [comment]
I agree, but I strongly suggest anyone doing validation check `jwt_get_alg()` against their expectation after running `jwt_decode()`

Rewriting this would require changing `jwt_decode()` to accept a new argument for expected algorithm but I'm leaning to create a new function called `jwt_validate()` that does nothing but check all aspects of the token (including `exp` and other items) and this seems like a better option in the long run.

Until then, the work around is to use `jwt_get_alg()` on the result of `jwt_decode()` to run the validation directly.

**Comment by big-kahuna-burger** [comment]
It's similar api to jsonwebtoken (node.js). There are `decode` and `verify` functions where first one is simply decoding content and second one is verifying against known alg beforehand, but not the one extracted from token, that one can be tampered and you can have a false positive as described in post. Known algorithm is passed as option to `verify` fn.

As mentioned in #58, agreed alg _should_ be loaded from config and passed down to `verify`.

**Comment by benmcollins** [comment]
Using LibJWT Validation functions alleviates this issue, and also the correct usage go decode should include checking jwt_get_alg().
