### ISSUE TITLE
Open SSL  version

### ISSUE THREAD

**Issue by daniel-piche** [benmcollins/libjwt#35]
Please document which version of OpenSSL our using.
I've spend lots of time find out which version to use.
OpenSSL-0.9.7m  doesn't compile  (but should not be used)
OpenSSL-1.1.0d   doesn't compile (EVP_PKEY doesn't contain 'type' member)
Find out  OpenSSL-1.0.2k that compile OK.

**Comment by zhiguangwang** [comment]
Also got the following errors with OpenSSL 1.1.0e:

```
jwt.c: In function 'jwt_sign_sha_pem':
jwt.c:448:10: error: dereferencing pointer to incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
  if (pkey->type != type)
          ^~

In file included from /opt/openssl/1.1.0e/include/openssl/asn1.h:24:0,
                 from /opt/openssl/1.1.0e/include/openssl/objects.h:916,
                 from /opt/openssl/1.1.0e/include/openssl/evp.h:27,
                 from jwt.c:23:
jwt.c:501:30: error: dereferencing pointer to incomplete type 'ECDSA_SIG {aka struct ECDSA_SIG_st}'
   r_len = BN_num_bytes(ec_sig->r);
                              ^
```

**Comment by benmcollins** [comment]
Can you tell me what OS/platform you're compiling on? I've not been able to reproduce that with any of the OpenSSL versions I'm compiling against (1.0.x/1.1.x/1.2.x).

I notice you're compiling against one in /opt, is there any chance you're getting conflicting headers from an OS installed OpenSSL and the one in /opt?

**Comment by zhiguangwang** [comment]
I'm compiling on Ubuntu 16.10, with latest OpenSSL and jansson self-compiled and installed into `/opt`.

The compile errors are pretty easy to reproduce with the following configure options:

```
PKG_CONFIG_PATH='/opt/jansson/2.10/lib/pkgconfig:/opt/openssl/1.1.0e/lib/pkgconfig' \
./configure \
    --enable-shared=no \
    --enable-static=yes \
    --prefix=/opt/libjwt/1.7.3
```

The reason it fails is the major API changes introduced in OpenSSL 1.1.0, see:

- [1.1 API Changes - OpenSSLWiki](https://wiki.openssl.org/index.php/1.1_API_Changes)
- [OpenSSL 1.1.0 Series Release Notes](https://www.openssl.org/news/openssl-1.1.0-notes.html)

I have created a pull request that resolves this issue.

**Comment by daniel-piche** [comment]
Thanks for sharing information.

________________________________
De : Zhiguang Wang <notifications@github.com>
Envoyé : 12 mars 2017 03:43
À : benmcollins/libjwt
Cc : daniel-piche; Author
Objet : Re: [benmcollins/libjwt] Open SSL version (#35)


I'm compiling on Ubuntu 16.10, with latest OpenSSL and jansson self-compiled and installed into /opt.

The compile errors are pretty easy to reproduce with the following configure options:

PKG_CONFIG_PATH='/opt/jansson/2.10/lib/pkgconfig:/opt/openssl/1.1.0e/lib/pkgconfig' \
./configure \
    --enable-shared=no \
    --enable-static=yes \
    --prefix=/opt/libjwt/1.7.3


The reason it fails is the major API changes introduced in OpenSSL 1.1.0, see:

  *   1.1 API Changes - OpenSSLWiki<https://wiki.openssl.org/index.php/1.1_API_Changes>
  *   OpenSSL 1.1.0 Series Release Notes<https://www.openssl.org/news/openssl-1.1.0-notes.html>

I have created a pull request that resolves this issue.

**Comment by benmcollins** [comment]
Current code works on OpenSSL 1.1.0f.
