### ISSUE TITLE
avoid change in grant.

### ISSUE THREAD

**Issue by warichet** [benmcollins/libjwt#39]
Pb:
Avoid change in grant. 
For example change exp grant.

Solution:
Sign JWT with grant key/value.
Add new function call in "jwt_set_alg()" and "jwt_decode()". 

That increase the size of signature but this avoid client change in grant part. 

Code:
int jwt_set_key(jwt_t *jwt, const unsigned char *key, int len)
{
	int grants_len = 0;

	const char *grants = json_string_value(jwt->grants);
	if (grants) {
		grants_len = strlen(grants);
	}
	// Allocate memory for key
	int key_len = len + grants_len;
	// TODO check minimum size

	jwt->key = malloc(key_len);
	if (!jwt->key)
		return ENOMEM;

	// First copy the configured key
	memcpy(jwt->key, key, len);
	// Second sign all grants
	if (grants) {
		memcpy(&(jwt->key[len]), grants, grants_len);
	}
	jwt->key_len = key_len;
	return 0;
}

Best regards
Sebastien

**Comment by benmcollins** [comment]
I really don't know what you're trying to accomplish here. Can you point to something in the JWT RFC that shows this use case?

**Comment by warichet** [comment]
It is about integrity of token.
It is to avoid any client change in grant. Mainly for expiration time.
If Client change the expiration time, The JWT will be rejected.
But your are right perhaps that should be coded outside of library. 

Best regards
Sebastien

**Comment by AnthonyDeroche** [comment]
A client cannot change any grant contained in the token without invalidating the signature. It is already implemented in the lib. See JWS pointed out by RFC 7515.

**Comment by benmcollins** [comment]
Yeah, the whole point of signing the token is so that the client can't change it without invalidating the signature. Otherwise, you can't trust it.

**Comment by benmcollins** [comment]
Closing, as this is outside the scope of a complaint JWT implementation.

**Comment by warichet** [comment]
Hello,

first sorry if it is losing time that is my last comment in this issue promise. :-) 
I have check to change expiration time grant in HTTP message generate/decoded using official libjwt.
And the two message are decoded as valid.

Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0ODc4ODE2Mz**B**9.9bR1Pkr2t4zTwNXnGUZXfwg6WEZb9Ef1sdKEdnr2zG0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0ODc4ODE2Mz**F**9.9bR1Pkr2t4zTwNXnGUZXfwg6WEZb9Ef1sdKEdnr2zG0

In code:
jwt_sign_sha_pem() and jwt_sign_sha_hmac() used only jwt->key to sign message.

Best regards
Sebastien
