### ISSUE TITLE
[FEATURE REQUEST] GnuTLS support

### ISSUE THREAD

**Issue by silvioprog** [benmcollins/libjwt#42]
Hello dudes,

Thanks for this awesome job!

So, it would be nice to choose between crypt engine OpenSSL(default) or GnuTLS. :-)

Thank you!

**Comment by babelouest** [comment]
Hi @silvioprog and @benmcollins ,

I'm currently working on porting libjwt for gnutls, so far all the tests pass, except for the ES256, ES384 and ES512 signatures. Right now it's a rework of libjwt without any openssl code but with a few macro it should be easy to select between openssl and gnutls on compilation.

For example, you could choose your backend library like this:
```shell
$ ./configure # Default, use OpenSSL
$ ./configure --with-gnutls # Use gnutls instead of OpenSSL
```

@benmcollins , are you interested to accept this change in master branch when it will be completed?

My work is available here:
https://github.com/babelouest/libjwt/tree/gnutls

**Comment by benmcollins** [comment]
I would definitely be interested, but only if it's abstracted so the implementation for each (OpenSSL and GnuTLS) are in a separate file. I would rather not have `ifdef`s sprinkled all over.

Thanks

**Comment by babelouest** [comment]
No problem then, but how about having 3 blocks in the `jwt.cv` file like:

```c
// Non cryptographic functions
jwt_add_grants()
jwt_set_alg()
// etc
#ifdef USE_OPENSSL
// All the cryptographic functions written for openssl
jwt_encode()
jwt_decode()
// etc.
#else // use Gnutls
// All the cryptographic functions written for Gnutls
jwt_encode()
jwt_decode()
// etc.
#endif
```

Like this it could all stay in the same file with minimum `ifdef` to keep the code readable and maintainable.

How about this?

**Comment by benmcollins** [comment]
But that's not maintainable. The jwt_en/decode functions may have changes in non-crypto-functionality that would have to be kept in sync. I would rather make an abstraction, and implement the abstraction in jwt_openssl.c and jwt_gnutls.c, and link to the one being used. This also allows for other possible implementations (e.g. NSS) without adding even more ifdefs.

**Comment by babelouest** [comment]
OK no problem. I'm preparing a `jwt-gnutls.c` file with gnutls encryption use.

I see that you are currently making deep changes to jwt. Should I wait for this job to be finished before sending a pull request?

**Comment by babelouest** [comment]
Other question: are you familiar enough with automake/autoconf to update the `Makefile.am` files for me to just push `jwt-gnutls.c` ?

I'm not that familiar with autoconf/automake so it could take some time for me, that's why I'm asking.

**Comment by benmcollins** [comment]
Yes, I would hold off. I'm Going to separate out the OpenSSL bits, and you can just copy that and rework it for GnuTLS.

If you can provide the implementation, I'll provide the hooks into the build.

Thanks

**Comment by babelouest** [comment]
Sure, I'll wait for your `go` then, thanks.

**Comment by benmcollins** [comment]
There is now a `jwt-openssl.c` that implements the four routines needed by LibJWT, which are listed in `jwt-private.h`. There's a sign/verify for each of HMAC and PEM (RSA/EC). If you can work that to implement the GnuTLS backend as `jwt-gnutls.c`, I'll incorporate it.

Thanks

**Comment by benmcollins** [comment]
Support has been added.

**Comment by silvioprog** [comment]
Thanks for implementing it @babelouest ! :+1:
