### ISSUE TITLE
jwt_decode should have an "alg" parameter

### ISSUE THREAD

**Issue by stan1y** [benmcollins/libjwt#43]
Recent security review by auth0 uncovered an issue with various JWT implementations:
https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

It seems like libjwt is affected as well.
https://github.com/benmcollins/libjwt/blob/master/libjwt/jwt.c#L781

**Comment by benmcollins** [comment]
As pointed out with other similar variations of this, we fully suggest that users check the `alg` type after verification to make sure it matches expectations. This can be done with `jwt_get_alg()`.

I'm trying to avoid changing the API for `jwt_decode()` in favor of implementing a `jwt_verify()` function that will include more thorough validations, including checking that the `alg` type matches expectations.

**Comment by stan1y** [comment]
I fully respect the notion to keep `jwt_decode` with current signature. And this is indeed a matter for a caller code to handle. But at the same time the fact that `jwt_decode` would accept alg=none makes libjwt implementation prone to misuse just like indicated in the article. This issue is mostly to start a discussion on what could be the best wat to mitigate misuse rather than indicate the fact.

**Comment by benmcollins** [comment]
There are two things that can be done without changing `jwt_decode()`'s API.

1) If `alg="none"` and the caller passed in a key, then it should fail with `EINVAL` or similar.
2) If `alg="none"` and the caller did not pass a key, but there is a signature portion in the JWT, then it should also fail with `EINVAL` or similar.

I think this would alleviate the ability for users to shoot themselves in the foot by not checking `jwt_get_alg()` after calling `jwt_decode()`.

**Comment by stan1y** [comment]
It seems like case (1) is already handled

**Comment by benmcollins** [comment]
That's correct. It's also tested for in a test case. That's the main offender, too. #2 would only happen if someone really tried to do something stupid, so I'm not even sure I want to implement it.

**Comment by stan1y** [comment]
At the moment `jwt_verify` is a static. I do accept the fact that `jwt_decode` leaves verification (i.e. check for everything to be expected) to a caller. Probably it just need to be stressed in the docs or something. Lets see if there is someone to point out if we're truly missing something here, since I am no security expert.

**Comment by benmcollins** [comment]
For this particular issue, if the user expects the signature to be validated, then they pass a key. If the JWT has `alg="none"`, then decode will fail. There's no further validation needed by the caller in this case.

**Comment by benmcollins** [comment]
This existing test case addresses and proves that your particular issue is non-existent in current libJWT code:

```START_TEST(test_jwt_decode_alg_none_with_key)
{
        const char token[] = "eyJhbGciOiJub25lIn0."
                             "eyJpc3MiOiJmaWxlcy5jeXBocmUuY29tIiwic"
                             "3ViIjoidXNlcjAifQ.";
        jwt_t *jwt;
        int ret;

        ret = jwt_decode(&jwt, token, (const unsigned char *)"key", 3);
        ck_assert_int_eq(ret, EINVAL);
        ck_assert(jwt == NULL);

        jwt_free(jwt);
}
END_TEST```
