### ISSUE TITLE
autoreconf error

### ISSUE THREAD

**Issue by fro0m** [benmcollins/libjwt#46]
autoreconf -i

Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

**Comment by benmcollins** [comment]
Your build tools are not installed correctly. Make sure you have automake, libtool, and autoconf installed

**Comment by fro0m** [comment]
OK, got it.
