### ISSUE TITLE
base64 decode bug on raspbian, raspberry pi 2, armv7l

### ISSUE THREAD

**Issue by babelouest** [benmcollins/libjwt#47]
Hello,

There are some problems with the base64 functions on a Raspberry PI 2, armv7l architecture, the problem does not exist on a common x86_64 architecture.

Basically, all the `jwt_decode` fail due to inconsistent base64 decoding.

For example, in the test `jwt_new:test_jwt_decode`, the head value is `eyJhbGciOiJub25lIn0`. This shoulb be decoded into the following string: `{"alg":"none"}`. Although, the decoded string is the following: `{"alg":"none"}>` with an additional character `>` at the end, this leads to a failed json parsing, therefore the whole decoding process fail.

**Comment by benmcollins** [comment]
Looks like the base64 implementation I used was not big-endian friendly. I was able to reproduce this on a PowerPC.

I've pulled in a cleaner and simpler implementation that passes the straight tests on PPC and x86, but it seems to be triggering something in `check-valgrind`. Still looking into that.
