### ISSUE TITLE
Features support

### ISSUE THREAD

**Issue by don-prog** [benmcollins/libjwt#48]
Hello, @benmcollins!
This is not a bug, but I want to be sure: 
On the https://jwt.io/ page your repository hasn't `iss`, `sub`, `aud`, `exp`, `iat` check features and hasn't `RS256` algorithm support, but using search I can find some examples in your repo with `iss`, `sub`, `aud`, `exp`, `iat` and `RS256` keywords. So, what is the status of these features in your project? Are they available?
In particular, I want to use your project for verifying Firebase ID tokens using C++. Is it possible? 
I just want to know this and understand all correctly before I start. 
Regards!

**Comment by benmcollins** [comment]
We do not directly support the `iss/sub/aud/exp/iat`, but you can manually check these.

I've put in a pull request for jwt.io. We do, in fact, support RS256/384/512 and ES256/384/512. Examples of the usage are in the `tests/` subdirectory of the project.
