### ISSUE TITLE
Does this library support RS256?

### ISSUE THREAD

**Issue by shahzeb1** [benmcollins/libjwt#50]
![image](https://user-images.githubusercontent.com/1383831/30780369-b712e680-a0bd-11e7-8060-6f3e10807d5a.png)

Does this library support ES256? I ask because [JWT.io](https://jwt.io/) seems to think it doesn't.

**Comment by benmcollins** [comment]
It supports RS256/384/512 and ES256/384/512. I sent a pull request to JWT.io awhile back to update this and it has never been merged.

**Comment by shahzeb1** [comment]
Thanks for clarifying.
