### ISSUE TITLE
Major security issue

### ISSUE THREAD

**Issue by AnthonyDeroche** [benmcollins/libjwt#6]
Hello,

Your library has a major security issue in the token validation step (in jwt_decode).
If the provided alg is none, it bypasses the whole signature check, even though a key is provided in arguments.
It allows an attacker to forge a valid token with any signature (even empty), as long as the alg is set to none.

This security issue is  thoroughly explained here: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

It suggests not to let the responsibility to the library to choose the algorithm based on alg header. It suggests to completely ignore this field. In your library, it means adding a parameter in the decoding process which is the algorithm, or at least testing that the provided key is null when bypassing the signature check.

I will be able to make a pull request if you agree with this.

Regards,
Anthony

**Comment by benmcollins** [comment]
Thanks for bringing this up. I remember when I coded this wondering how best to handle it. I should have added a comment to revisit it later.

I agree with the explanation and your suggested fix. Please do send the pull request.

**Comment by benmcollins** [comment]
Fixed by 766e4350cb993a14a7de26883aa8021292be2203
