### ISSUE TITLE
help

### ISSUE THREAD

**Issue by herono2010** [benmcollins/libjwt#63]
when i execute  “autoreconf -i” ,  I make a mistake：

configure:12172: error: possibly undefined macro: AM_DEFAULT_VERBOSITY
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

my operation is Ubuntu 12.04.5 LTS;
autoconf version is 2.68;

Look forward to your answer，thanks

**Comment by benmcollins** [comment]
It's likely the AC prerequisite needs to be higher than 2.68. I've not tried to compile it on anything older than 14.04. Since 12.04 LTS is not even supported by Canonical anymore, I'm not sure it's worth it to work on supporting it with LibJWT. Perhaps you could update to 14.04 LTS or newer?

You could remove these two lines from configure.ac and retry:

    AX_VALGRIND_CHECK
    
    AX_CODE_COVERAGE

**Comment by herono2010** [comment]
My company won't update operating system easily. by remove "AX_VALGRIND_CHECK AX_CODE_COVERAGE",  Mistakes still exist。

**Comment by benmcollins** [comment]
Try using this tar all where autoreconf doesn’t need to be run. 

https://launchpad.net/~ben-collins/+archive/ubuntu/libjwt/+files/libjwt_1.8.0.orig.tar.xz

**Comment by benmcollins** [comment]
The other alternative is to generate the autoreconf on a 14.04 or newer system, then copy the entire directory to the 12.04 system for building.

Last resort, try using cmake to build.

**Comment by benmcollins** [comment]
I'm full of suggestions today!. You can also try getting the prebuilt packages for Trusty (14.04) and see if they work on 12.04:

    sudo add-apt-repository ppa:ben-collins/libjwt
    sudo apt-get update

Make sure apt points to trusty for my PPA.

    deb http://ppa.launchpad.net/ben-collins/libjwt/ubuntu trusty main

**Comment by herono2010** [comment]
i use operation ubuntu 14.04;
opessl version: OpenSSL 1.0.1f

when i execute “./configure” , I make a mistake：

./configure: line 11488: syntax error near unexpected token `OPENSSL,'
./configure: line 11488: `	PKG_CHECK_MODULES(OPENSSL, openssl >= 0.9.8)'

but i have installed the openssl . the error is a syntax error?

**Comment by endlisnis** [comment]
I'm running into the same problem using autoreconf v2.69 in CentOS v6.5.  Oddly enough, when I run in CentOS v7.5 using the same version of autoreconf (v2.69), I do NOT get this problem.
