### ISSUE TITLE
Requires too recent cmake version

### ISSUE THREAD

**Issue by arhuaco** [benmcollins/libjwt#64]
Hi there!

I am building with _Debian stretch_ and the configuration failed because the distro ships with cmake 3.7.

I managed to build with this change so I think you are asking for a version that is too recent.

    --- a/CMakeLists.txt
    +++ b/CMakeLists.txt
    @@ -1,4 +1,4 @@
    -cmake_minimum_required (VERSION 3.9)
    +cmake_minimum_required (VERSION 3.0)

Cheers!

PS: Let me know if you want me to send the trivial patch that fixes the issue.

**Comment by benmcollins** [comment]
Thanks for the report. CMake is not the primary build system for LibJWT, so I don't personally test it. At most, I would change it to 3.7, since that is what you were able to test with.

**Comment by benmcollins** [comment]
Fixed in Commit 7a26ab4230ecfde4a3daac5ea81eaa77999f37f5
