### ISSUE TITLE
error: storage size of ‘token’ isn’t known

### ISSUE THREAD

**Issue by Blobby19** [benmcollins/libjwt#66]
Hello,
When i declare my token as jwt_t I get the error as in the title of this thread.
`#include <jwt.h>`
`jwt_t token;`
I link shared library in CFLAGS: `-ljwt`
I never get this error before and is not well documented in google.
Someone already facing this issue ?
Thank you in advance.

**Comment by benmcollins** [comment]
You need to declare it as:

    jwt_t *token;

**Comment by Blobby19** [comment]
Thank you.
