### ISSUE TITLE
Support user-defined header claims (e.g. kid)

### ISSUE THREAD

**Issue by noisy62** [benmcollins/libjwt#68]
I was trying to use libjwt to generate Apple Music Developer Token, however it seems no place to found where to set kid header parameter?

**Comment by benmcollins** [comment]
Can you elaborate on what "kid header parameter" is?

Also, check.h is in GNU Check library. You need that in order to compile the test suite (`make check`)

**Comment by benmcollins** [comment]
I just looked into this. What I really need to do is allow arbitrary header values. Something that LibJWT doesn't do, at the moment.

**Comment by noisy62** [comment]
kid is an optional header in JWT standard RFC7515:
4.1.4.  "kid" (Key ID) Header Parameter

   The "kid" (key ID) Header Parameter is a hint indicating which key
   was used to secure the JWS.  This parameter allows originators to
   explicitly signal a change of key to recipients.  The structure of
   the "kid" value is unspecified.  Its value MUST be a case-sensitive
   string.  Use of this Header Parameter is OPTIONAL.

   When used with a JWK, the "kid" value is used to match a JWK "kid"
   parameter value.

a typical Apple Music Developer Token payload is like:
{
    "alg": "ES256",
    "kid": "ABC123DEFG"
}
{
    "iss": "DEF123GHIJ",
    "iat": 1437179036,
    “exp”: 1493298100
 }

For now I will just modify the source by adding a new function with additional parameter based on jwt_encode(). But for the future, it is nice to have the feature for libjwt to be able to add optional headers.

**Comment by noisy62** [comment]
Hi Ben!
I added a command line utility program amdevtok on the base of libjwt. Modified jwt.h/jwt.c to add 2 customized functions. The work is in a clone: https://github.com/noisy62/amdevtok. IMHO, it will be useful to expand the jwt_t structure to accommodate optional header parameters. But for this sole purpose of Apple Music Developer Token creation, a little hack is enough. Thanks for your work!!!

**Comment by marek-kuzora** [comment]
I would also love to get header parameters support. Right now I have no way of extracting kid from google provided jwt and therefore I don't know which key use to verify the signature (google jwt structure: https://firebase.google.com/docs/auth/admin/verify-id-tokens).

What's the ETA on fixing this bug?

**Comment by hcngac** [comment]
#71 Please review and see if this is useful

**Comment by benmcollins** [comment]
This is resolved with some commits that were just merged.

**Comment by marek-kuzora** [comment]
Great, thanks!
