### ISSUE TITLE
Generating RSA private and public keys

### ISSUE THREAD

**Issue by arun11299** [benmcollins/libjwt#70]
Hello,
This is more of question than an issue. How did you generate the RSA private and public keys ?
I am doing this:
ssh-keygen -t rsa -b 4096 -f jwtRS256.key
/usr/local/Cellar/openssl/1.0.2j/bin/openssl pkcs8 -topk8 -outform PEM -in jwtRS256.key -out jwtRS256.key.pem --nocrypt

I get below error (with and without step#2):
PEM_read_bio_PrivateKey failed: error:0906D06C:lib(9):func(109):reason(108)

Thanks

**Comment by benmcollins** [comment]
You don't want to use SSH to generate your RSA keys.

https://rietta.com/blog/2012/01/27/openssl-generating-rsa-key-from-command/

**Comment by arun11299** [comment]
It still fails for me.
The example generates the key starting with "-----BEGIN RSA PRIVATE KEY-----". But your sample has it starting with "-----BEGIN PRIVATE KEY-----".
I tried converting them to PKCS8 format as well:
/usr/local/Cellar/openssl/1.0.2j/bin/openssl pkcs8 -topk8 -inform pem -in file.key -outform pem -nocrypt -out file.pem

I am sure I am doing something stupid.

**Comment by arun11299** [comment]
Ignore the above. I had made a booboo.

Thanks.
