### ISSUE TITLE
Extend ubuntu ppa to include a bionic Release

### ISSUE THREAD

**Issue by r-chris** [benmcollins/libjwt#73]
When trying to install `libjwt` via your `ppa` I see this issue:
```
Err:8 http://ppa.launchpad.net/ben-collins/libjwt/ubuntu bionic Release                                        
  404  Not Found [IP: 91.189.95.83 80]
```

Presumably there is no version available for the current Ubuntu 18.04 LTS (bionic).
It would be great if that would become available.

**Comment by r-chris** [comment]
Looks like there already is a package here:
https://launchpad.net/ubuntu/bionic/+source/libjwt

**Comment by benmcollins** [comment]
Right. I only maintain for Ubuntu releases prior to when they started including it.

Thanks
