### ISSUE TITLE
java jwt can not  decode

### ISSUE THREAD

**Issue by OIUE** [benmcollins/libjwt#88]
then java jwt can not decode
the jwt_decode return not 0

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJoZWxsbyIsIm5iZiI6MTQ4ODgxOSwiZXhwIjoxOTA4ODM1fQ.OKJ-3sOiXFgJr37xT6SIohzfQQLS7iaHYvNCd7WatuA

who can help me

**Comment by benmcollins** [comment]
I'll need your 256-bit secret that was used to encode this in order to help.'

Also, the "code" you're using and the actual return value from jwt_decode.

**Comment by benmcollins** [comment]
No response.
