### ISSUE TITLE
CMake build incomplete

### ISSUE THREAD

**Issue by jt416** [benmcollins/libjwt#91]
The automake build produces static and dynamic library. CMake instructions only produce one or other.

CMake install does not include header installation.

And it might be nice export a LibJwtConfig.cmake to make it easier to integrate into other CMake projects.

**Comment by benmcollins** [comment]
I don't maintain the CMake build, so someone else would need to do this.

**Comment by maddanio** [comment]
i will give it a shot. the cmake build is much more stable than the autotools one (besides these issues)

**Comment by maddanio** [comment]
ah, it seems the header is actually installed

**Comment by benmcollins** [comment]
Not sure what you mean by stable, but the autotools build with LibJWT is better maintained as it's the only one I use and it's the only one tested with the Travis-CI integration.

Since the header is in fact installed, would you consider this closed?

**Comment by maddanio** [comment]
i made a pr to deploy config files

**Comment by dafanasiev** [comment]
Also `cmake install` does not make symlinks with lib version:

`autotools install`:

```sh
ls -la /usr/local/lib/
total 312
-rw-r--r--    1 root     root        154200 Sep  7 07:58 libjwt.a
-rwxr-xr-x    1 root     root           934 Sep  7 07:58 libjwt.la
lrwxrwxrwx    1 root     root            15 Sep  7 07:58 libjwt.so -> libjwt.so.1.8.1
lrwxrwxrwx    1 root     root            15 Sep  7 07:58 libjwt.so.1 -> libjwt.so.1.8.1
-rwxr-xr-x    1 root     root        146464 Sep  7 07:58 libjwt.so.1.8.1
drwxr-xr-x    2 root     root          4096 Sep  7 07:58 pkgconfig
```

`cmake install`:

```sh
ls -la /usr/local/lib/
-rw-r--r-- 1 root root 51936 сен  7 11:09 libjwt.so
```

**Comment by benmcollins** [comment]
Since I don't maintain the CMake build, I'm going to assume this is either fixed or no one cares to fix it.
