### ISSUE TITLE
Can't decode jti grant (HS256)

### ISSUE THREAD

**Issue by georgii-ivanov** [benmcollins/libjwt#92]
Trying to execute this code:

```
                         jwt_t *jwt = NULL;
			jwt_decode(&jwt, token, (const unsigned char *)SESSION_KEY_APP_SECRET, 0);
			const char *account = jwt_get_grant(jwt, "jti");
			jwt_free(jwt);
			printf(SESSION_KEY_APP_SECRET);
			printf(token);
			printf(account);
```

Key:
`red cat wears hat`

Token:
eyJhbGciOiJIUzI1NiJ9.NWQxOTUxYzI0NzI2OTAzNDIyMjRiOTlm.OWEWwvFwAHUMvSCs5Nx-S1cpgx14unCkkMUjjgYOX9E

Output:
`
red cat wears hat
eyJhbGciOiJIUzI1NiJ9.NWQxOTUxYzI0NzI2OTAzNDIyMjRiOTlm.OWEWwvFwAHUMvSCs5Nx-S1cpgx14unCkkMUjjgYOX9E

`

Expected: UUID stored inside jti "5a8b392c-f3b6-42ac-bc42-07d4ff11eb2e"

Please help to get what's the problem there. Thank you!

**Comment by benmcollins** [comment]
a) What is the value of `account` after calling `jwt_get_grant()`?
b) You free'd the JWT, which frees the memory that `account` points to. You would want to `strdup()` this value before freeing the JWT, but check to make sure it's not `NULL` first.

**Comment by benmcollins** [comment]
I take it back. I put this token on http://JWT.io and it shows that the payload is empty. The JTI grant does not exist in the token, this `jwt_get_grant()` is definitely going to return NULL.

You need to fix your token.

**Comment by benmcollins** [comment]
<img width="907" alt="Screen Shot 2019-10-10 at 12 17 56 AM" src="https://user-images.githubusercontent.com/320303/66538687-760c9780-eaf3-11e9-8a2c-fde9742e462d.png">

**Comment by georgii-ivanov** [comment]
@benmcollins 

Sorry but NodeJS is able to decode this jwt token for some reason :O
I'm kinda surprised. I know it's not your bad as long as jwt online tools says that it has no payload but:

```
jwt.verify(authToken, config.secret,  async (err, account) => {
            console.log('DECODED:', account);
});
````

Produces this output:

```eyJhbGciOiJIUzI1NiJ9.NWQxOTUxYzI0NzI2OTAzNDIyMjRiOTlm.OWEWwvFwAHUMvSCs5Nx-S1cpgx14unCkkMUjjgYOX9E red cat wears hat
DECODED: 5d1951c2472690342224b99f```

Payload is: `5d1951c2472690342224b99f`

So I use 3M+ library https://www.npmjs.com/package/jsonwebtoken for NodeJS.

Do you have maybe some guesses what's wrong?

Also this token is produced by same NodeJS library too.

**Comment by georgii-ivanov** [comment]
![image](https://user-images.githubusercontent.com/1070139/66539740-cfbe9300-eaee-11e9-9803-092f968a0a73.png)
I tried to make the same token in online debugger and it worked. But there is error "Invalid Signature". Eh... Idk what's it... but probably NodeJS also makes token with invalid signature

**Comment by georgii-ivanov** [comment]
Okay.. I guess I got it. @benmcollins 

But now checked valid token doesn't work too...
```
			jwt_t *jwt = NULL;
			jwt_decode(&jwt, "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImlzcyI6IjVkMTk1MWMyNDcyNjkwMzQyMjI0Yjk5ZiJ9.e30.ZpCkhhr3_ttfmkXqShnbOn4p5nnSlolCWzMoMury6wI", (unsigned char *)"red cat wears hat", 0);
			const char *account = jwt_get_grant(jwt, "iss");
			jwt_free(jwt);
			printf(SESSION_KEY_APP_SECRET);
			printf(account);
```

I guess I'm still doing something wrong...

![image](https://user-images.githubusercontent.com/1070139/66540976-48275300-eaf3-11e9-8965-5edea280b683.png)

**Comment by benmcollins** [comment]
That's not a valid JWT payload, though. The payload is supposed to be a JSON string with grants and such in it. Something like this:

    {"iat":1475980545,"iss":"foo.example.com","somenums":["one","two"]}

So while you might be able to get it to "decode", the payload is not JSON, as expected, which means LibJWT will not be able to return values from it.

**Comment by georgii-ivanov** [comment]
@benmcollins  yeah I've got all of this. I didn't know completely how jwt works...
Now it's all works as a charm :) ty for the lib 👍
